// iOS (Swift) interview deck. Typed data is the source of truth — edit directly.
// Generated by scripts/gen-study-content.mjs from the study-content workflow, then
// fact-checked. Hand-edits are preserved; re-run the generator only to regenerate.
import type { Subject } from "../types";

export const iosSubject: Subject = {
  "id": "ios",
  "label": "iOS (Swift)",
  "short": "iOS",
  "blurb": "Swift, memory, concurrency, UIKit & SwiftUI.",
  "cards": [
    {
      "id": "ios-swift-1",
      "category": "swift",
      "categoryLabel": "SWIFT LANGUAGE",
      "question": "How do you handle optionals safely? When do you reach for `if let` vs `guard let`, and why is force-unwrap a code smell?",
      "answer": "An optional is just an enum (`.some`/`.none`) that makes \"absence\" explicit in the type system, so the compiler forces you to deal with `nil` instead of crashing at runtime.\n\nMy toolkit:\n\n- `guard let x else { return }` for **early-exit** unwrapping — it keeps `x` in scope for the rest of the function and flattens the happy path, so I reach for it at the top of a method.\n- `if let x` (shorthand) when the value is only needed inside a **narrow branch**.\n- `??` to supply a default (`name ?? \"Guest\"`), and optional chaining (`user?.profile?.avatarURL`) to short-circuit a whole chain to `nil` instead of nesting checks.\n\nForce-unwrap (`!`) is a smell because it asserts \"never nil\" and **traps** if you're wrong — it trades a compile-time guarantee for a crash. I only allow it for genuine programmer-error invariants (e.g. a hardcoded `URL(string:)!`), never for data from the network or a user.",
      "level": "mid"
    },
    {
      "id": "ios-swift-2",
      "category": "swift",
      "categoryLabel": "SWIFT LANGUAGE",
      "question": "Struct vs class — how do you decide, and what does value vs reference semantics actually change in practice?",
      "answer": "Structs are **value types**: assigning or passing one copies it, so each holder gets an independent instance with no shared identity. Classes are **reference types**: holders share one heap instance, and they add inheritance, identity (`===`), and deinitializers.\n\nApple's guidance, which I follow: **default to a struct**, reach for a class only when you need reference semantics — shared mutable state, identity, inheritance, or Objective-C / `NSObject` interop.\n\nValue semantics kill a class of aliasing bugs: a struct can't be mutated out from under you. The nuance is **copy-on-write** — `Array`, `String`, and `Dictionary` are structs but only copy their backing storage on mutation, so you get value semantics without copying on every pass. Also, `let` on a struct freezes all its stored properties, whereas `let` on a class only freezes the reference, not the object's `var` properties.",
      "level": "mid"
    },
    {
      "id": "ios-swift-3",
      "category": "swift",
      "categoryLabel": "SWIFT LANGUAGE",
      "question": "What is protocol-oriented programming, and how does it differ from classic OOP inheritance?",
      "answer": "POP models capabilities as **protocols** and shares behavior through **protocol extensions** rather than a base-class hierarchy. Instead of \"this `is-a` Animal,\" you say \"this `can` Fly\" — a type conforms to many small protocols, which composes far better than single inheritance and lets value types (structs, enums) participate in polymorphism, which class inheritance can't give them.\n\nThe enabling feature is the **protocol extension**: a default method implementation every conformer gets for free without a shared superclass.\n\nThe senior nuance is dispatch: a method that's a **protocol requirement** uses dynamic (witness-table) dispatch, so a conformer's implementation is honored through a protocol-typed variable. But a method that exists **only** in the extension (not in the requirement list) uses static dispatch — so a conformer's \"override\" of it won't be called through a protocol-typed reference. Knowing that line is what separates correct default-implementation design from subtle bugs.",
      "level": "senior"
    },
    {
      "id": "ios-swift-4",
      "category": "swift",
      "categoryLabel": "SWIFT LANGUAGE",
      "question": "Explain generics in Swift. What problem do they solve, and how do constraints and associated types fit in?",
      "answer": "Generics let you write one type-safe implementation over **any** type instead of duplicating code or falling back to `Any` and casting. `func swap<T>(_ a: inout T, _ b: inout T)` works for every `T`, checked at the call site — no runtime casts, no boxing.\n\nConstraints narrow what `T` can be so you can actually use it: `func max<T: Comparable>(...)` requires `Comparable` so `<` is available, and `where` clauses add richer requirements (`where T.Element: Equatable`).\n\nFor **protocols**, the equivalent of a type parameter is an **associated type** (`associatedtype Element`) — that's why `Collection` is generic over `Element` without angle brackets. The senior nuance: a protocol with associated types or `Self` requirements can't be a plain existential — you reach for `some` (opaque types, one concrete type fixed by the implementation) or `any` (a boxed existential). Preferring generics or `some` over `any` usually means specialization and better performance, since `any` carries dynamic-dispatch and boxing overhead.",
      "level": "senior"
    },
    {
      "id": "ios-swift-5",
      "category": "swift",
      "categoryLabel": "SWIFT LANGUAGE",
      "question": "Why are enums with associated values so useful in Swift? Give a concrete modeling example.",
      "answer": "A Swift enum can attach a **different payload to each case**, so it models a value that is exactly one of several mutually exclusive shapes — and the compiler forces you to handle each. This is the idiomatic way to make illegal states unrepresentable.\n\nThe canonical example is a load state:\n\n- `enum LoadState { case idle; case loading; case loaded([Item]); case failed(Error) }`\n\nNow `loaded` carries its items and `failed` carries its error, but you can't have items *and* an error at once — the type makes that impossible. You destructure with a `switch` and binding: `case .loaded(let items):`. `Optional` and `Result<Success, Failure>` are themselves just enums with associated values.\n\nThe nuance: an exhaustive `switch` turns adding a new case into a **compile error** at every call site — exactly the safety net you want as the model grows, far better than a struct of optional fields where invalid combinations slip through.",
      "level": "mid"
    },
    {
      "id": "ios-swift-6",
      "category": "swift",
      "categoryLabel": "SWIFT LANGUAGE",
      "question": "Explain Swift's error handling: `throws`, `try`, `do/catch`, and the `try?` / `try!` variants. How does it differ from exceptions?",
      "answer": "A function that can fail is marked `throws` and signals with `throw someError`, where the error is any value conforming to `Error` (usually an enum). Callers **must** prefix a throwing call with `try`, which makes failure points visible — it's explicit, typed control flow, not invisible stack-unwinding, and it has no runtime cost on the success path.\n\nThe variants:\n\n- `do { try f() } catch { ... }` to handle the error, often `switch`-ing over a typed error enum.\n- `try?` converts a throw into an **optional** (`nil` on failure) when you don't care why.\n- `try!` asserts it won't throw and **traps** if it does — same smell as force-unwrap, only for true invariants.\n- An uncaught `try` inside a `throws` function propagates to its caller.\n\nNuance: errors propagate one frame at a time (no automatic multi-frame unwind like exceptions), `defer` blocks still run during propagation for cleanup, and Swift 6 added **typed throws** (`throws(MyError)`) to constrain the thrown type.",
      "level": "mid"
    },
    {
      "id": "ios-mem-1",
      "category": "memory",
      "categoryLabel": "MEMORY",
      "question": "What is ARC, and how does it differ from a tracing garbage collector?",
      "answer": "**ARC** (Automatic Reference Counting) is a compile-time mechanism: the Swift compiler inserts `retain`/`release` calls so a class instance is deallocated the instant its strong reference count hits zero. There is no runtime collector scanning the heap.\n\nA tracing GC (JVM, Go) runs periodically, walks the object graph from roots to find what's reachable, and frees the rest on its own schedule.\n\nKey differences:\n- **Determinism:** ARC frees objects immediately and predictably, so `deinit` runs at a known point; a tracing GC frees later, non-deterministically.\n- **Pauses vs overhead:** ARC has no stop-the-world pause, but pays for atomic retain/release traffic on every ownership change.\n- **Cycles:** a tracing GC reclaims reference cycles automatically; ARC cannot, so you break them with `weak`/`unowned`.\n\nARC governs only reference types (classes, and the boxed storage behind closures), not value types like structs and enums.",
      "level": "mid"
    },
    {
      "id": "ios-mem-2",
      "category": "memory",
      "categoryLabel": "MEMORY",
      "question": "Explain the difference between strong, weak, and unowned references.",
      "answer": "All three describe how a reference participates in ARC's reference count.\n\n- **strong** (the default): increments the retain count and keeps the object alive — the owner.\n- **weak**: does not increment the count, must be an `Optional`, and is automatically set to `nil` when the referent deallocates. Safe to outlive the object.\n- **unowned**: does not increment the count and is non-optional; it is *not* zeroed on dealloc, so accessing it after the referent is gone traps (a deliberate crash), or is undefined behavior with `unowned(unsafe)`.\n\nSenior nuance: choose `unowned` only when the reference is guaranteed to have an equal-or-longer lifetime than self. It skips the optional unwrap and the runtime side-table bookkeeping that `weak` requires, but when in doubt prefer `weak` for safety.",
      "level": "mid"
    },
    {
      "id": "ios-mem-3",
      "category": "memory",
      "categoryLabel": "MEMORY",
      "question": "What is a retain cycle, and how do you break one?",
      "answer": "A **retain cycle** (strong reference cycle) happens when two or more objects hold strong references to each other, so neither's retain count ever reaches zero. ARC never frees them and the memory leaks, even though nothing outside the cycle can reach them.\n\nThe classic case is a parent holding a child strongly while the child holds the parent strongly; another is an object owning a closure that captures `self` strongly.\n\nYou break the cycle by making one edge non-owning:\n- Use `weak` for a back-reference that may legitimately become `nil` (a delegate, a child pointing back at its parent).\n- Use `unowned` when the back-reference is guaranteed never to outlive the object it points to, so it can never dangle.\n\nThe fix is always to demote exactly one direction of the cycle to a non-strong reference so the count can drain to zero.",
      "level": "mid"
    },
    {
      "id": "ios-mem-4",
      "category": "memory",
      "categoryLabel": "MEMORY",
      "question": "Explain closure capture lists and when you need `[weak self]`.",
      "answer": "Closures are reference types and capture the variables they use by **strong** reference by default. If `self` stores a closure that also references `self`, you get a retain cycle.\n\nA capture list `[weak self]` (or `[unowned self]`) at the start of the closure overrides that, capturing `self` without incrementing its count. With `[weak self]`, `self` becomes an `Optional` inside the closure, so you typically `guard let self else { return }` to unwrap it for the body.\n\nWhen you need it:\n- The closure is **stored/escaping** and outlives the current scope (a property, a network completion handler, a Combine `sink`).\n- You do **not** need it for non-escaping closures that run synchronously and return, like `map`/`filter`, since the closure is released when the call returns.\n\nSenior nuance: prefer `[weak self]` over `[unowned self]` for async/escaping work whose completion timing you don't control; `unowned` there risks a crash if `self` deallocates first.",
      "level": "senior"
    },
    {
      "id": "ios-mem-5",
      "category": "memory",
      "categoryLabel": "MEMORY",
      "question": "Why are delegate properties declared `weak`?",
      "answer": "Because the delegating object and its delegate usually end up owning each other. A view controller creates and strongly holds a view; the view exposes a `delegate` pointing back at the controller. If that `delegate` were strong, you'd have a two-way retain cycle and both would leak.\n\nDeclaring `weak var delegate: SomeDelegate?` makes the back-reference non-owning, so the count can drain and both objects deinit correctly.\n\nSenior details:\n- The protocol must be class-bound (`protocol SomeDelegate: AnyObject`) for the property to be `weak`, since `weak` requires a reference type.\n- The owner is responsible for the delegate's lifetime; the delegating object just borrows it. If the delegate deallocates, the property auto-nils — exactly the safe behavior you want.\n- It's a convention, not a rule: a delegate that genuinely owns its source (rare) could be strong, but `weak` is the default to avoid leaks.",
      "level": "senior"
    },
    {
      "id": "ios-mem-6",
      "category": "memory",
      "categoryLabel": "MEMORY",
      "question": "How do you use Xcode's Memory Graph Debugger to find a leak?",
      "answer": "The **Memory Graph Debugger** pauses the running app and snapshots every live object plus the reference edges between them. You trigger it from the debug bar (the three-node graph icon) while the app runs.\n\nTo hunt a retain cycle:\n- Exercise the suspect flow (e.g. push and pop a screen several times), then capture the graph.\n- Xcode flags suspected leaks with a purple `!` runtime-issue badge; filtering the navigator to leaked objects surfaces them.\n- Select an object and read the inbound arrows to see *who* retains it. A cycle shows up as a closed loop of strong edges; an object that should be gone but isn't reveals the unexpected owner.\n- Enabling **Malloc Stack Logging** in the scheme lets the inspector show each object's allocation backtrace, pinpointing where the leaked instance was created.\n\nComplementary tools: the **Leaks** and **Allocations** instruments track growth over time, but the Memory Graph is the fastest way to see the exact ownership edge to break.",
      "level": "senior"
    },
    {
      "id": "ios-conc-1",
      "category": "concurrency",
      "categoryLabel": "CONCURRENCY",
      "question": "In GCD, how do the main queue and a global queue differ, and what does QoS actually control?",
      "answer": "GCD schedules work onto a shared pool of threads via queues, so you never create or manage threads yourself.\n\n- `DispatchQueue.main` is a **serial** queue bound to the main thread; all UIKit/SwiftUI updates must run here.\n- `DispatchQueue.global(qos:)` returns a **concurrent** queue backed by the shared thread pool, for background work.\n- **QoS** (`.userInteractive`, `.userInitiated`, `.utility`, `.background`) is a classification the system uses to prioritize CPU, I/O throughput, and scheduling — it is not a thread count or a hard guarantee.\n\nSenior nuance: GCD fights **priority inversion** via QoS propagation — when a high-QoS item waits (e.g. a `sync` onto a lower-QoS queue), the system temporarily boosts the lower-QoS work. Prefer `async` over `sync` to avoid deadlocking the calling queue.",
      "level": "mid"
    },
    {
      "id": "ios-conc-2",
      "category": "concurrency",
      "categoryLabel": "CONCURRENCY",
      "question": "How does async/await work under the hood, and how is a Task different from spinning up a thread?",
      "answer": "`await` marks a **suspension point**: the function can give the thread back to the cooperative pool while it waits, then resumes — possibly on a *different* thread — when the awaited work completes. No thread is blocked during the suspension.\n\nA `Task` is a unit of asynchronous work, not a thread. The runtime multiplexes many tasks onto a small cooperative pool (about one thread per core), so thousands of tasks don't spawn thousands of threads.\n\nSenior nuance: never assume thread identity survives an `await`, and never make blocking calls (`semaphore.wait()`, sync I/O) inside async code — you'd starve the pool and risk deadlock. Reach for `Task.detached` only when you deliberately want to escape the current actor and priority context.",
      "level": "mid"
    },
    {
      "id": "ios-conc-3",
      "category": "concurrency",
      "categoryLabel": "CONCURRENCY",
      "question": "What problem do actors solve, and how is @MainActor different from a regular actor?",
      "answer": "An `actor` is a reference type that protects its mutable state by serializing access: only one task touches its isolated state at a time, giving data-race safety without manual locks. Calls from *outside* the actor are `async` and hop onto the actor's executor.\n\n`@MainActor` is a **global actor** whose executor is the main thread. Annotating a type, method, or property with it guarantees that code runs on the main thread — the modern, compiler-checked replacement for `DispatchQueue.main.async`.\n\nSenior nuance: beware **actor reentrancy** — across an `await` inside one of its methods, an actor can interleave other tasks, so invariants that held before the suspension may not hold after. Re-check state after every `await`.",
      "level": "senior"
    },
    {
      "id": "ios-conc-4",
      "category": "concurrency",
      "categoryLabel": "CONCURRENCY",
      "question": "What is Sendable, and why does the compiler force you to think about it?",
      "answer": "`Sendable` is a marker protocol meaning a value is **safe to pass across a concurrency boundary** (between tasks, actors, or threads) without introducing a data race. The compiler requires anything crossing such a boundary to be `Sendable`.\n\n- A value type is automatically `Sendable` when all its stored members are `Sendable`.\n- Immutable classes, or classes that synchronize internally, can be `@unchecked Sendable` — you assert correctness the compiler can't prove.\n- Closures crossing boundaries become `@Sendable`, which forbids capturing mutable non-`Sendable` state.\n\nSenior nuance: under Swift 6 / strict concurrency this is enforced at compile time, turning whole classes of runtime races into build errors. `@unchecked Sendable` is an escape hatch, not a fix — use it only with a real synchronization mechanism (a lock, a queue) behind it.",
      "level": "senior"
    },
    {
      "id": "ios-conc-5",
      "category": "concurrency",
      "categoryLabel": "CONCURRENCY",
      "question": "What is structured concurrency, and how do task groups and async let give you cancellation and error propagation for free?",
      "answer": "Structured concurrency ties child task lifetimes to a parent scope: the scope can't return until all its children finish, so there are no leaked, orphaned tasks. Cancellation propagates down the tree and errors propagate up automatically.\n\n- `async let` starts a child that runs concurrently and is awaited within the same scope — ideal for a fixed set of parallel calls; if you never await it, it's cancelled at scope exit.\n- `withTaskGroup` / `withThrowingTaskGroup` handles a dynamic number of children; if one throws, the throwing group cancels the remaining siblings.\n\nSenior nuance: cancellation is **cooperative** — a child keeps running until it checks `Task.isCancelled` or hits a cancellation-aware point like `try Task.checkCancellation()`. A tight CPU-bound loop must poll it explicitly or it ignores cancellation entirely.",
      "level": "senior"
    },
    {
      "id": "ios-conc-6",
      "category": "concurrency",
      "categoryLabel": "CONCURRENCY",
      "question": "How would you wrap a legacy completion-handler API in async/await, and what's the one trap with continuations?",
      "answer": "Bridge it with `withCheckedThrowingContinuation` (or the non-throwing variant), resuming the continuation from inside the existing callback:\n\n- On success call `continuation.resume(returning:)`, on error `resume(throwing:)`.\n- If the callback is `Result`-shaped, `continuation.resume(with: result)` handles both cases.\n\nThe critical contract: a continuation must be resumed **exactly once**. Resuming twice traps; never resuming hangs the awaiting task forever (the checked variant logs a warning). The `withChecked...` variants catch these misuses; drop to `withUnsafeContinuation` only as a measured optimization after you've proven correctness.\n\nSenior nuance: forward cancellation too. Wrap the call in `withTaskCancellationHandler` so cancelling the awaiting task cancels the underlying operation (e.g. a `URLSessionTask`); otherwise the wrapper silently ignores structured cancellation.",
      "level": "senior"
    },
    {
      "id": "ios-ui-1",
      "category": "ui",
      "categoryLabel": "UIKIT & SWIFTUI",
      "question": "Walk through the UIViewController lifecycle. Why is `viewDidLayoutSubviews` the right place for frame-based work, and what's the trap with `viewWillAppear`?",
      "answer": "The order is `loadView` -> `viewDidLoad` (once, view loaded but not yet sized) -> `viewWillAppear` -> `viewIsAppearing` -> `viewWillLayoutSubviews` -> `viewDidLayoutSubviews` -> `viewDidAppear`, with the `willDisappear`/`didDisappear` pair on the way out.\n\nDo one-time setup in `viewDidLoad`, but never rely on final bounds there or in `viewWillAppear` — the view still has its nib/storyboard frame, not its laid-out size. Work that needs real geometry (manual frames, a `CAGradientLayer` resize, a `cornerRadius` from the width) belongs in `viewDidLayoutSubviews`, which the system calls every time the size changes.\n\nThe trap with `viewWillAppear` is it fires on **every** appearance — returning from a pushed controller, dismissing a sheet — so it's right for refreshing state but wrong for one-time setup, and it runs before the layout pass so bounds are unreliable. The senior nuance: `viewIsAppearing` (iOS 17, back-deployed) sits just after it with trait collection and bounds already resolved.",
      "level": "mid"
    },
    {
      "id": "ios-ui-2",
      "category": "ui",
      "categoryLabel": "UIKIT & SWIFTUI",
      "question": "Explain Auto Layout's constraint system: what is `intrinsicContentSize`, and how do content hugging and compression resistance break ambiguity between two labels in a row?",
      "answer": "Auto Layout solves a system of linear constraints (`item1.attr = m * item2.attr + c` at a given priority) via the Cassowary algorithm; the solution sets every view's frame. A view's `intrinsicContentSize` is the natural size it reports (a label's text width, an image's pixel size), which the engine treats as implicit size constraints at the hugging/resistance priorities.\n\nWhen two labels share a row and there isn't space for both at intrinsic size, priorities decide who gives:\n\n- **Content hugging** (default 250) resists *growing* past intrinsic size — the higher-hugging view stays tight while the lower one stretches.\n- **Compression resistance** (default 750) resists *shrinking* below intrinsic size — the higher-resistance view keeps its text while the lower one truncates.\n\nThe senior nuance: prefer tuning these priorities over hard width constraints, since hardcoded widths trigger `UIViewAlertForUnsatisfiableConstraints` conflicts under Dynamic Type or localization.",
      "level": "senior"
    },
    {
      "id": "ios-ui-3",
      "category": "ui",
      "categoryLabel": "UIKIT & SWIFTUI",
      "question": "`@StateObject` vs `@ObservedObject` — what's the actual difference, and what bug appears if you use `@ObservedObject` to create a view model?",
      "answer": "Both wrap an `ObservableObject` and subscribe the view to its `objectWillChange` publisher. The difference is **ownership and lifetime**: `@StateObject` makes the view the owner — SwiftUI instantiates the object once and keeps it alive across re-renders of that view. `@ObservedObject` holds a reference the view does *not* own, for an object passed in from elsewhere.\n\nThe classic bug is `@ObservedObject var vm = ViewModel()`. Because the view struct is recreated on every parent re-render, that initializer runs again and the view model is silently reset — losing in-flight state, cancelling work, restarting timers. `@StateObject` guarantees a single instantiation.\n\nThe rule: the view that *creates* the object uses `@StateObject`; views that *receive* it use `@ObservedObject` (or `@EnvironmentObject` for deep passing).",
      "level": "mid"
    },
    {
      "id": "ios-ui-4",
      "category": "ui",
      "categoryLabel": "UIKIT & SWIFTUI",
      "question": "How does the `@Observable` macro (Observation framework) change state management compared to `ObservableObject` / `@Published`, and why is it more efficient?",
      "answer": "`@Observable` (iOS 17+, the Observation framework) replaces the `ObservableObject` + `@Published` + Combine machinery. You annotate a class with `@Observable` and its stored properties become trackable automatically — no per-property wrapper.\n\nThe efficiency win is **per-property dependency tracking** instead of object-level invalidation. With `ObservableObject`, any `@Published` change fires `objectWillChange`, so every view observing that object re-evaluates even if it read an unrelated property. `@Observable` records exactly which properties a view's `body` *reads* and invalidates only views that touched the property that actually changed.\n\nUsage simplifies too: you hold the model with plain `let` or `@State` (no `@StateObject`/`@ObservedObject` split), use `@Bindable` to derive bindings into it, and `@Environment(Model.self)` instead of `@EnvironmentObject`. The nuance: tracking is read-driven, so a property read inside a closure that runs after `body` (not during it) won't establish a dependency.",
      "level": "senior"
    },
    {
      "id": "ios-ui-5",
      "category": "ui",
      "categoryLabel": "UIKIT & SWIFTUI",
      "question": "Explain SwiftUI view identity and how it drives diffing. What goes wrong when you give `ForEach` an unstable `id`, and when do you reach for `.id()`?",
      "answer": "SwiftUI diffs by **identity**, not by the view struct (structs are cheap value types it recreates constantly). Identity is either *structural* (a view's position in the tree) or *explicit* (`id:` on `ForEach`, or `.id(_:)`). When identity is stable across updates, SwiftUI treats it as the same view — preserving `@State`, animating the transition. When identity changes, it tears down the old view and builds a fresh one, resetting state.\n\nAn unstable `ForEach` id — an array index, or a `UUID()` generated inline in `body` — assigns new identities every render, so SwiftUI destroys and rebuilds rows. Symptoms: lost scroll position, broken animations, a row's `@State` resetting, and wasted work. Use a stable `Identifiable` key (a model's persistent id).\n\nYou reach for explicit `.id(value)` deliberately when you *want* a hard reset — bumping the id forces SwiftUI to discard and recreate the subtree (e.g. fully resetting a form), the inverse of the bug above.",
      "level": "senior"
    },
    {
      "id": "ios-ui-6",
      "category": "ui",
      "categoryLabel": "UIKIT & SWIFTUI",
      "question": "It's 2026 and you're starting a new screen. How do you decide UIKit vs SwiftUI, and how do you bridge when you can't pick just one?",
      "answer": "Default to SwiftUI for new work — it's Apple's strategic direction, far less code, and gives you state-driven UI, Dynamic Type, and dark mode largely for free. Reach for UIKit at its concrete gaps: fine-grained `UICollectionView` control (custom compositional layouts, complex cell reuse/prefetching at scale), precise text editing, camera/`AVFoundation` view work, mature third-party SDKs that ship UIKit views, or supporting OS versions below the SwiftUI API you need.\n\nThe senior framing is that it's rarely all-or-nothing — you bridge:\n\n- `UIViewRepresentable` / `UIViewControllerRepresentable` to embed UIKit inside SwiftUI (with a `Coordinator` for delegates).\n- `UIHostingController` to drop a SwiftUI view into a UIKit navigation stack.\n\nNuance: keep a clear ownership boundary so state isn't duplicated across the bridge — pick one framework as the source of truth for a given screen and let the other render it.",
      "level": "senior"
    },
    {
      "id": "ios-life-1",
      "category": "lifecycle",
      "categoryLabel": "APP LIFECYCLE",
      "question": "How did the app lifecycle change with iOS 13, and what is the split of responsibilities between `UIApplicationDelegate` and `UISceneDelegate`?",
      "answer": "Before iOS 13, `UIApplicationDelegate` owned both the **process** lifecycle and the **UI/window** lifecycle. iOS 13 introduced scenes to support multiple windows (multi-window on iPad, multiple instances of one app), so those two concerns were split.\n\n- `UIApplicationDelegate` keeps **process-level** events: `didFinishLaunchingWithOptions`, push registration, and vending scene configurations via `application(_:configurationForConnecting:options:)`.\n- `UISceneDelegate` owns the **per-scene UI/window lifecycle**: `sceneDidBecomeActive`, `sceneWillResignActive`, `sceneDidEnterBackground`, and building the `UIWindow` in `scene(_:willConnectTo:)`.\n\nThe senior nuance: once an app opts into scenes (a `UIApplicationSceneManifest` in `Info.plist`), the legacy `UIApplication` UI callbacks like `applicationDidBecomeActive` **stop firing** — you must use the scene callbacks, because one process can hold several scenes in different states at once.",
      "level": "mid"
    },
    {
      "id": "ios-life-2",
      "category": "lifecycle",
      "categoryLabel": "APP LIFECYCLE",
      "question": "Walk me through the five app execution states and the transitions between them.",
      "answer": "The states are **not running, inactive, active, background, and suspended**.\n\n- **Active**: in the foreground and receiving events.\n- **Inactive**: foreground but not receiving events (mid-transition, during a system alert, or in the App Switcher). UI is visible but you shouldn't assume input.\n- **Background**: not visible but still executing code briefly, on the way to suspension or while holding a background task / running a background mode.\n- **Suspended**: in memory but executing no code; the system can purge it under memory pressure with no notification.\n\nKey nuance: there's no direct active to background transition. You always pass through **inactive** first (`sceneWillResignActive`), then `sceneDidEnterBackground`, then the system suspends you once any background work finishes.",
      "level": "junior"
    },
    {
      "id": "ios-life-3",
      "category": "lifecycle",
      "categoryLabel": "APP LIFECYCLE",
      "question": "In the SwiftUI `App` lifecycle, how do you observe state changes without a `UIApplicationDelegate`?",
      "answer": "SwiftUI exposes lifecycle through the environment value `@Environment(\\.scenePhase)`, a `ScenePhase` enum with cases `.active`, `.inactive`, and `.background` — there is no `suspended` case, since suspension runs no code.\n\nYou react with `.onChange(of: scenePhase)` on a `Scene` or `View`, for example flushing state to disk when it becomes `.background`.\n\nThe senior nuance: for process-level hooks SwiftUI doesn't surface (push-token registration, `didFinishLaunching`, third-party SDK init), you bridge back to UIKit with `@UIApplicationDelegateAdaptor`, which attaches a real `UIApplicationDelegate` to a pure-SwiftUI app.",
      "level": "mid"
    },
    {
      "id": "ios-life-4",
      "category": "lifecycle",
      "categoryLabel": "APP LIFECYCLE",
      "question": "An app needs ~20 seconds to finish an upload after the user backgrounds it. How do you keep it running, and what are the limits?",
      "answer": "For short finite work, wrap it in `beginBackgroundTask(withName:expirationHandler:)` and call `endBackgroundTask` when done. This buys extra wall-clock time before suspension, typically around 30 seconds (`backgroundTimeRemaining` reports what's left).\n\nThe expiration handler is mandatory: it must cancel the work and call `endBackgroundTask` synchronously. If you never end the task, the watchdog kills the app with `0x8badf00d`.\n\nThe senior nuance: a background task is the wrong tool for a real, possibly slow upload. The correct approach is `URLSession` with a **background configuration**, which hands the transfer to the system `nsurlsessiond` daemon so it completes — and relaunches your app to handle the result — even after your process is suspended or terminated.",
      "level": "senior"
    },
    {
      "id": "ios-life-5",
      "category": "lifecycle",
      "categoryLabel": "APP LIFECYCLE",
      "question": "Compare the main background execution mechanisms: BGAppRefreshTask, BGProcessingTask, background URLSession, and silent push.",
      "answer": "The system schedules all of these opportunistically based on battery, network, and usage — you don't get guaranteed timing. Their `Info.plist` requirements differ, which trips people up.\n\n- **BGAppRefreshTask** (BGTaskScheduler): short (~30s) content refreshes; needs the `fetch` background mode plus a `BGTaskSchedulerPermittedIdentifiers` entry. Runs while the device is in use.\n- **BGProcessingTask**: longer maintenance (minutes), can require power/network, e.g. DB cleanup; needs the `processing` mode plus the same permitted-identifiers entry. Typically runs overnight on charge.\n- **Background URLSession**: out-of-process transfers via the system daemon, surviving suspension/termination; requires **no** `UIBackgroundModes` entry.\n- **Silent push** (`content-available: 1`): server-initiated wake to fetch data; needs the `remote-notification` mode and is rate-limited and coalesced by the system.\n\nThe nuance: BGTaskScheduler replaced the legacy `setMinimumBackgroundFetchInterval` API, splitting refresh vs. processing semantics with explicit constraints.",
      "level": "senior"
    },
    {
      "id": "ios-life-6",
      "category": "lifecycle",
      "categoryLabel": "APP LIFECYCLE",
      "question": "How does UIKit state restoration work, and when would you use it over manually persisting state?",
      "answer": "State restoration rebuilds your UI to where the user left off after the system terminates a suspended app to reclaim memory, so it feels like it was never killed. In the scene-based world it's driven by a `stateRestorationActivity` (`NSUserActivity`) returned from `UISceneDelegate` and re-applied in `scene(_:willConnectTo:)`; the legacy path uses `restorationIdentifier` plus `encodeRestorableState`/`decodeRestorableState`.\n\nCrucially, it only triggers on **system termination** — not on a user force-quit from the App Switcher, not on reboot, not on app update. So it's a UX nicety, not a durability guarantee.\n\nThe senior nuance: don't conflate it with data persistence. Restoration captures **navigation/UI state** (which screen, selection, scroll offset); anything the user must not lose still needs explicit persistence to disk or a database. Modern apps increasingly express this via `NSUserActivity`, which also feeds Handoff and Spotlight.",
      "level": "senior"
    },
    {
      "id": "ios-net-1",
      "category": "networking",
      "categoryLabel": "NETWORKING",
      "question": "What are URLSession's three task types, and when do you reach for each?",
      "answer": "`URLSession` exposes three concrete task types, each tuned for a transfer shape:\n\n- `URLSessionDataTask` — buffers the request/response in memory; the default for JSON APIs and small payloads.\n- `URLSessionDownloadTask` — streams the body to a temp file on disk, so large responses don't balloon memory; it's the only type that supports `resumeData` to resume an interrupted transfer.\n- `URLSessionUploadTask` — sends a file or `Data` body and reports upload progress.\n\nThe key distinction is **memory vs. disk**: data tasks hold the whole response in RAM, while download/upload tasks stream to/from files. Pair download/upload tasks with a background `URLSessionConfiguration` for transfers that must keep running after the app is suspended.",
      "level": "mid"
    },
    {
      "id": "ios-net-2",
      "category": "networking",
      "categoryLabel": "NETWORKING",
      "question": "How does Codable map JSON to Swift types, and how do you handle key-naming and date mismatches?",
      "answer": "`Codable` is `Encodable & Decodable`; the compiler synthesizes a `CodingKeys` enum from your stored property names, and `JSONDecoder`/`JSONEncoder` match those keys against the JSON.\n\nFor mismatches, prefer configuration over hand-written code:\n\n- snake_case keys: set `decoder.keyDecodingStrategy = .convertFromSnakeCase`, or override individual `CodingKeys` cases for one-off renames.\n- dates: set `decoder.dateDecodingStrategy` (e.g. `.iso8601`, or `.custom` / a `DateFormatter` — note `.iso8601` rejects fractional-second timestamps).\n\nWrite a custom `init(from:)` only when the shape genuinely diverges — flattening nested objects or decoding polymorphic types. Senior nuance: make absent fields actual `Optional` properties so a missing key decodes to `nil` instead of throwing `keyNotFound`.",
      "level": "mid"
    },
    {
      "id": "ios-net-3",
      "category": "networking",
      "categoryLabel": "NETWORKING",
      "question": "How do you write a modern async URLSession request, and what does async/await buy you over completion handlers?",
      "answer": "Use `let (data, response) = try await URLSession.shared.data(for: request)`. It suspends the calling task instead of nesting a closure, errors propagate with `try`, and the request is cancelled automatically when the enclosing `Task` is cancelled.\n\nThe payoff over completion handlers is linear control flow, free structured cancellation, and no thread-hop or retain-cycle bookkeeping. You must still cast `response as? HTTPURLResponse` and check `statusCode` yourself — a 404 or 500 is a successful transport call, not a thrown error.\n\nSenior nuance: honor cooperative cancellation with `try Task.checkCancellation()` around long pipelines, and use `URLSession.bytes(for:)` for streaming/SSE so you process the response incrementally instead of buffering it all.",
      "level": "senior"
    },
    {
      "id": "ios-net-4",
      "category": "networking",
      "categoryLabel": "NETWORKING",
      "question": "How do you design error handling and retries for a networking layer? Which errors are retryable?",
      "answer": "Separate the failure classes: transport failures surface as `URLError` (`.notConnectedToInternet`, `.timedOut`, `.networkConnectionLost`), while server failures arrive as a successful response carrying a 4xx/5xx `statusCode` you must inspect manually.\n\nOnly retry **idempotent, transient** failures — timeouts, connection-lost, and 5xx/429 — and never blindly retry a non-idempotent POST. Back off with exponential delay plus jitter to avoid a thundering herd, cap the attempt count, and honor a `Retry-After` header when present.\n\nSenior nuance: 4xx other than 408/429 are caller bugs and should fail fast; check `URLError.code == .cancelled` and abort rather than retry a user-cancelled request; centralize the policy in one wrapper so it's uniform and testable.",
      "level": "senior"
    },
    {
      "id": "ios-net-5",
      "category": "networking",
      "categoryLabel": "NETWORKING",
      "question": "How does URLSession response caching work, and how do you control it?",
      "answer": "`URLSession` caches HTTP responses through `URLCache` (there's a shared default), driven by the server's `Cache-Control`/`ETag`/`Expires` headers and the request's `cachePolicy`. On a hit with a validator, the framework issues a conditional request (`If-None-Match`/`If-Modified-Since`); a 304 returns the stored body without re-downloading.\n\nTune it per request via `URLRequest.cachePolicy` (e.g. `.reloadIgnoringLocalCacheData` to force-fetch, `.returnCacheDataElseLoad` for offline-first), or globally by sizing a custom `URLCache` on the `URLSessionConfiguration`.\n\nSenior nuance: only cacheable `GET`s are stored, background sessions and ephemeral configurations bypass the cache, the on-disk store isn't encrypted (don't cache sensitive bodies), and you can rewrite or veto caching in the `urlSession(_:dataTask:willCacheResponse:)` delegate.",
      "level": "senior"
    },
    {
      "id": "ios-net-6",
      "category": "networking",
      "categoryLabel": "NETWORKING",
      "question": "How do you implement certificate or public-key pinning in URLSession, and what are the operational trade-offs?",
      "answer": "Handle the `URLSessionDelegate` authentication callback `urlSession(_:didReceive:completionHandler:)`. For a `serverTrust` challenge, first let the system validate the chain with `SecTrustEvaluateWithError`, then compare the server's certificate or — preferably — its public-key (SPKI) hash against a pinned set; respond with `.useCredential(URLCredential(trust:))` on match or `.cancelAuthenticationChallenge` on mismatch.\n\nPin the **public key**, not the full certificate, so routine cert renewals that reuse the key don't break the app. The operational risk is bricking clients if the key rotates, so always ship a backup pin.\n\nArchitect nuance: prefer declarative `NSPinnedDomains` in Info.plist when you can, which moves enforcement into the OS networking stack; remember pinning defends against rogue/compromised CAs but adds a hard operational dependency on key lifecycle and forces an app update to rotate pins.",
      "level": "architect"
    },
    {
      "id": "ios-persist-1",
      "category": "persistence",
      "categoryLabel": "PERSISTENCE",
      "question": "When would you use UserDefaults versus Keychain, and why is a token in UserDefaults a red flag?",
      "answer": "`UserDefaults` is a `plist`-backed key-value store for small, non-sensitive preferences (theme, last tab, feature flags). It is fast but written as an unencrypted plist in the app container and captured in unencrypted Finder/iTunes backups, so it must never hold secrets.\n\nKeychain is the encrypted store for credentials: tokens, passwords, keys. Items are encrypted at rest, the keys are protected by the device's hardware (Secure Enclave on supported devices), and an accessibility class (e.g. `kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly`) controls when an item is readable and whether it syncs or survives a restore.\n\nThe red flag: a token in `UserDefaults` is readable by anyone with the unencrypted backup or filesystem access, and it can ride along in an iCloud backup to a new device.",
      "level": "junior"
    },
    {
      "id": "ios-persist-2",
      "category": "persistence",
      "categoryLabel": "PERSISTENCE",
      "question": "Explain the Core Data context hierarchy and the threading rule. How do you do background work safely?",
      "answer": "An `NSManagedObjectContext` is a single-queue scratchpad of managed objects backed by an `NSPersistentStoreCoordinator`. The cardinal rule: a context and its `NSManagedObject`s are confined to that context's queue, so you touch them only inside `perform` or `performAndWait`. The only thing safe to pass across contexts is an `NSManagedObjectID`.\n\nWith `NSPersistentContainer` you get a main-queue `viewContext` for UI, and you spawn background work via `performBackgroundTask`, which gives a private-queue context wired directly to the coordinator (not a child of `viewContext`); its save goes straight to the store.\n\nSenior nuance: set `viewContext.automaticallyMergesChangesFromParent = true` and pick a merge policy (e.g. `NSMergeByPropertyObjectTrumpMergePolicy`) so background saves reconcile into the UI without you hand-merging `NSManagedObjectContextDidSave` notifications.",
      "level": "mid"
    },
    {
      "id": "ios-persist-3",
      "category": "persistence",
      "categoryLabel": "PERSISTENCE",
      "question": "What knobs on an NSFetchRequest matter for performance, and what mistake kills it on large datasets?",
      "answer": "A naive `NSFetchRequest` faults every matching row into memory as full objects. The knobs that matter:\n\n- `fetchBatchSize` so rows load lazily in batches as you scroll, not all at once.\n- `fetchLimit` / `fetchOffset` for paging.\n- `predicate` and `sortDescriptors` pushed down to SQLite, backed by indexed attributes.\n- `resultType = .dictionaryResultType` with `propertiesToFetch` when you only need a few columns.\n\nThe classic mistake is filtering or sorting in Swift after fetching everything, instead of letting SQLite do it via the predicate. For driving a list, an `NSFetchedResultsController` with a batch size is the right tool because it manages sections, change tracking, and memory.",
      "level": "mid"
    },
    {
      "id": "ios-persist-4",
      "category": "persistence",
      "categoryLabel": "PERSISTENCE",
      "question": "How does SwiftData relate to Core Data, and what are the real tradeoffs of adopting it?",
      "answer": "SwiftData is a Swift-native layer built on the same Core Data foundation (it shares the SQLite store and the underlying object-graph concepts). You declare models with the `@Model` macro instead of an `.xcdatamodeld`, query with `#Predicate` and `@Query`, and use `ModelContainer` / `ModelContext` in place of container and context.\n\nThe wins are type safety, value-type-feeling models, automatic SwiftUI binding via `@Query`, and far less boilerplate. `@ModelActor` gives you a concurrency-isolated context for background work.\n\nTradeoffs to name: it is iOS 17+; the macro-driven API still trails mature Core Data on complex migrations, fine-grained fetch control, and child contexts (iOS 18 closed some gaps like indexes and history but not all); and the generated layer is harder to debug. For a greenfield iOS 17+ app I'd reach for it; for a large Core Data app I'd interoperate gradually rather than rewrite.",
      "level": "senior"
    },
    {
      "id": "ios-persist-5",
      "category": "persistence",
      "categoryLabel": "PERSISTENCE",
      "question": "Walk me through the app sandbox directories. Where do you put a downloaded cache versus user-created documents, and why does it matter?",
      "answer": "Each app runs in a sandboxed container. The directories to know:\n\n- `Documents/` — user-generated content you can't regenerate; backed up, and visible in Files if you opt in.\n- `Library/Application Support/` — app data the user didn't create directly (your database); backed up, hidden.\n- `Library/Caches/` — regenerable data; not backed up, and the OS can purge it under disk pressure.\n- `tmp/` — short-lived scratch; can be deleted anytime.\n\nIt matters because Apple rejects apps that store large re-downloadable caches in `Documents` (it bloats iCloud backups), and putting truly precious data in `Caches` means the system can silently delete it. For files you must keep but don't want backed up, set the `isExcludedFromBackup` resource key explicitly.",
      "level": "mid"
    },
    {
      "id": "ios-persist-6",
      "category": "persistence",
      "categoryLabel": "PERSISTENCE",
      "question": "A new feature needs to persist data. How do you choose between UserDefaults, Keychain, files, SQLite/GRDB, and Core Data/SwiftData?",
      "answer": "I drive the choice off the data's shape, size, sensitivity, and query needs rather than defaulting to Core Data.\n\n- Small, non-sensitive settings: `UserDefaults`.\n- Secrets and credentials: Keychain.\n- Large opaque blobs (images, exports, downloads): the file system, with the right sandbox directory and backup exclusion.\n- A graph of related entities with relationships, change tracking, and SwiftUI binding: Core Data or SwiftData.\n- Heavy relational querying or a schema I want full control over: SQLite directly via GRDB, for explicit SQL, predictable migrations, and easy concurrency.\n\nThe senior framing: Core Data/SwiftData buy you object-graph management and faulting but cost you an opaque migration story, so I don't reach for them just to store a flat list. I also hide the choice behind a repository protocol, so swapping the store later doesn't ripple through the app.",
      "level": "architect"
    },
    {
      "id": "ios-perf-1",
      "category": "perf",
      "categoryLabel": "PERFORMANCE",
      "question": "A list scrolls smoothly in debug on the simulator but janks on a real device. Walk me through finding the cause in Instruments.",
      "answer": "I profile a **Release** build on a real device, because debug disables compiler optimizations and the simulator runs on the Mac's CPU/memory, so its timings don't reflect the phone.\n\n- **Time Profiler** samples the call stack on a timer; with \"Hide System Libraries\" on and the call tree inverted, the heaviest main-thread frames point straight at my hot function.\n- **Allocations** tracks live vs. transient allocations; a generational mark between two heap snapshots shows what a single scroll pass keeps allocating.\n- **Leaks** catches memory the app can no longer reach (usually a retain cycle); for cycles you still hold a pointer to (abandoned memory, not a true leak) the **Memory Graph Debugger** is sharper.\n\nThe senior move is measuring first to learn whether it's CPU, allocation churn, or off-screen layout, rather than optimizing on a hunch.",
      "level": "senior"
    },
    {
      "id": "ios-perf-2",
      "category": "perf",
      "categoryLabel": "PERFORMANCE",
      "question": "Why is keeping work off the main thread so critical on iOS, and how do you decide what moves off?",
      "answer": "The main thread owns UIKit/SwiftUI rendering and touch handling. The display refreshes every ~16.6ms at 60Hz (~8.3ms at 120Hz on ProMotion); if a main-thread task overruns that window the system misses a vsync and the user sees a dropped frame or a hitch.\n\nSo anything not strictly UI — JSON decoding, disk/network I/O, image decode and resize, hashing, heavy diffing — moves to a background queue (`DispatchQueue.global(qos:)` or work on a non-main actor), and I hop to the main actor only to mutate UI. Senior nuances: most UIKit drawing isn't thread-safe (`UIGraphicsImageRenderer` is the modern thread-safe exception), and over-dispatching tiny tasks adds context-switch overhead — so I batch work and leave the main thread doing only what must be on it.",
      "level": "mid"
    },
    {
      "id": "ios-perf-3",
      "category": "perf",
      "categoryLabel": "PERFORMANCE",
      "question": "Explain cell reuse in UITableView/UICollectionView. What bugs does getting it wrong cause, and how does this map to SwiftUI lists?",
      "answer": "Reuse keeps a small pool sized to the visible area and recycles off-screen cells via `dequeueReusableCell(withIdentifier:)` instead of allocating one per row, so a 10,000-row list only ever instantiates a dozen or so cells.\n\nThe classic bug is stale state: a reused cell still shows the **previous** row's image or text. The fix is `prepareForReuse()` to reset mutable state, plus guarding async results — when an image download returns, confirm the cell still maps to the same item (by indexPath or model identity) before applying it, or the wrong image flashes on the wrong row.\n\nIn SwiftUI, `List` and `LazyVStack` create rows lazily and discard off-screen ones rather than reusing instances; the equivalent discipline is a **stable `id`** so SwiftUI keeps identity and diffs correctly instead of rebuilding rows on every update.",
      "level": "mid"
    },
    {
      "id": "ios-perf-4",
      "category": "perf",
      "categoryLabel": "PERFORMANCE",
      "question": "Loading full-resolution images into thumbnails tanks scroll performance and memory. What's actually going wrong and how do you fix it?",
      "answer": "A `UIImage` is compressed on disk but **decoded** into an uncompressed bitmap in memory — roughly width x height x 4 bytes — so a 4000x3000 photo costs ~48MB no matter the 100pt thumbnail it lands in. Decode also happens lazily on the main thread at draw time, which is what stalls the scroll.\n\nThe fix is **downsampling**: `CGImageSourceCreateThumbnailAtIndex` with `kCGImageSourceThumbnailMaxPixelSize` (target size in pixels) plus `kCGImageSourceCreateThumbnailFromImageAlways`, decoding straight to the size you need off the main thread. The senior nuance is to force-decode ahead of display so the main thread never decodes mid-scroll, and to cap an `NSCache` so the bitmap cache stays inside the memory budget.",
      "level": "senior"
    },
    {
      "id": "ios-perf-5",
      "category": "perf",
      "categoryLabel": "PERFORMANCE",
      "question": "App launch feels slow. Distinguish the launch phases and what concretely you'd do to improve cold launch.",
      "answer": "I separate **cold** launch (process not resident — full dyld load, runtime init, first frame) from **warm/resume** (process still in memory). The cold path is what users feel, and Apple's guidance is under ~400ms to first frame.\n\nPre-`main` time is dynamic linking and `+load`/static initializers, so I cut dynamic framework count, avoid `+load` and heavy global constructors, and let dyld's prebuilt launch closure do its job. Post-`main`, the rule is **do nothing in `application(_:didFinishLaunchingWithOptions:)` that isn't needed to draw the first screen** — defer analytics SDKs, migrations, and prefetch to after first frame or to background work.\n\nI measure with the **App Launch** Instruments template (the modern replacement for eyeballing `DYLD_PRINT_STATISTICS`) and watch `MetricKit`'s launch histograms from the field rather than trusting one device.",
      "level": "senior"
    },
    {
      "id": "ios-perf-6",
      "category": "perf",
      "categoryLabel": "PERFORMANCE",
      "question": "A SwiftUI screen re-renders far more than expected. How does body re-evaluation work and how do you minimize it?",
      "answer": "SwiftUI re-invokes a view's `body` when a dependency it reads changes. Re-running `body` is itself cheap; the cost is when it cascades into child re-evaluation and layout.\n\nTechniques:\n- **Scope state narrowly.** Put `@State` on the smallest subview that needs it; hoisting state too high is the most common cause of over-rendering.\n- **Adopt Observation** (`@Observable`, iOS 17+): views re-render only when the **specific properties they actually read** change, versus `ObservableObject` where any `@Published` mutation invalidates every observer.\n- **Avoid minting fresh reference identities or closures in `body`**, and keep value types `Equatable` so SwiftUI can skip redundant diffs.\n\nThe senior tell is confirming with `Self._printChanges()` (or the SwiftUI Instrument) to see *what* invalidated, instead of scattering `EquatableView` blindly.",
      "level": "architect"
    }
  ]
};
