// React Native interview deck. Typed data is the source of truth — edit directly.
// Generated by scripts/gen-study-content.mjs from the study-content workflow, then
// fact-checked. Hand-edits are preserved; re-run the generator only to regenerate.
import type { Subject } from "../types";

export const reactNativeSubject: Subject = {
  "id": "react-native",
  "label": "React Native",
  "short": "RN",
  "blurb": "Architecture, rendering, performance, native modules.",
  "cards": [
    {
      "id": "rn-core-1",
      "category": "core",
      "categoryLabel": "ARCHITECTURE",
      "question": "What was the old async bridge, and how does JSI change the relationship between JS and native?",
      "answer": "The legacy bridge was an **asynchronous, batched message queue** between the JS and native realms. Calls and their arguments were serialized to JSON and shipped across in batches, so the two sides could never call each other synchronously and neither held a reference to the other's objects.\n\n`JSI` (JavaScript Interface) is a lightweight C++ layer that lets the JS engine hold **direct references to native objects** as `HostObject`s and call their methods synchronously, with no JSON serialization.\n\nThe nuance: JSI is engine-agnostic (it abstracts over Hermes, JSC, V8), and that synchronous, type-safe access is the foundation every other New Architecture piece (TurboModules, Fabric) is built on.\n\n**JSI is why New Architecture code calls native synchronously — no bridge, no JSON, no batching.**",
      "level": "senior"
    },
    {
      "id": "rn-core-2",
      "category": "core",
      "categoryLabel": "ARCHITECTURE",
      "question": "In the New Architecture, what do Fabric and TurboModules each replace, and what do they gain?",
      "answer": "Both are built on `JSI`.\n\n- **Fabric** is the new renderer. It replaces the old UIManager/async shadow-tree path with a C++ core that builds an immutable shadow tree and can commit synchronously, enabling things the old path couldn't — synchronous layout measurement and consistent reads via `useLayoutEffect`.\n- **TurboModules** replace the old NativeModules. Instead of eagerly initializing every module at startup and calling it over the bridge, they are **lazily loaded** and invoked synchronously through JSI.\n\nThe nuance: Fabric also lets React and native share one shadow tree across the render, commit, and mount phases, removing whole classes of out-of-order update bugs.\n\n**Fabric and TurboModules both trade eager, bridged access for lazy, synchronous JSI calls.**",
      "level": "senior"
    },
    {
      "id": "rn-core-3",
      "category": "core",
      "categoryLabel": "ARCHITECTURE",
      "question": "What is Hermes, and why does shipping bytecode matter for startup performance?",
      "answer": "**Hermes** is the JS engine Meta built specifically for React Native, optimized for mobile constraints rather than long-running server workloads.\n\nIts key trick is **ahead-of-time compilation to bytecode (`.hbc`)** at build time. The app ships precompiled bytecode instead of raw JS source, so at startup the engine skips the expensive parse-and-compile step and starts executing almost immediately — the main driver of Hermes's faster **TTI** (time to interactive).\n\nThe nuance: Hermes deliberately ships without a JIT to favor low memory use and small size, and its bytecode is memory-mappable, so the OS can lazily page it in instead of loading everything up front.\n\n**Hermes wins TTI by shipping precompiled bytecode, not by being a faster interpreter.**",
      "level": "mid"
    },
    {
      "id": "rn-core-4",
      "category": "core",
      "categoryLabel": "ARCHITECTURE",
      "question": "Name the three core threads in React Native and what each owns.",
      "answer": "- **JS thread** — runs your React code, business logic, and the JS bundle on the engine (Hermes/JSC). Block it and state updates and callbacks stall.\n- **UI / main thread** — the native platform thread that handles rendering, touch events, and native view manipulation. Block it and the actual UI and animations freeze.\n- **Background / shadow thread** — runs the Yoga flexbox layout engine off the main thread before handing computed positions to the UI thread.\n\nThe nuance: this separation is why a `useNativeDriver` animation stays smooth while the JS thread is busy — it runs on the UI side and never waits on JS. (Under Fabric, layout moves into the C++ renderer rather than a separate JS-driven shadow queue.)\n\n**Taps stop responding? Suspect the JS thread. Animations freeze? Suspect the UI thread.**",
      "level": "mid"
    },
    {
      "id": "rn-core-5",
      "category": "core",
      "categoryLabel": "ARCHITECTURE",
      "question": "Why did the old batched bridge cause jank, especially in lists and gestures?",
      "answer": "Every cross-realm call was **serialized to JSON, batched, and sent asynchronously**, which produced three failure modes:\n\n- The bridge is a single queue — flooding it with rapid scroll events or many small updates congests it, so updates arrive late.\n- Serialization itself costs CPU and grows with payload size.\n- Because it was async, native could never synchronously ask JS \"how tall is this row?\", so fast scrolling outran JS and showed blank cells.\n\nThe classic symptom is a `FlatList` flinging faster than JS can render, leaving white space.\n\nThe nuance: the bridge was an asynchronous boundary even for operations that conceptually needed to be synchronous — exactly what JSI's direct, synchronous calls fix.\n\n**The bridge forced an async boundary on work that was conceptually synchronous — that's the bug JSI fixes.**",
      "level": "senior"
    },
    {
      "id": "rn-core-6",
      "category": "core",
      "categoryLabel": "ARCHITECTURE",
      "question": "What is Codegen in the New Architecture, and what problem does it solve?",
      "answer": "**Codegen** is a build-time tool that reads your TurboModule and Fabric component **spec files** (typed JS/TS interfaces, e.g. `Native*` specs) and generates the C++/Java/Obj-C glue that binds JS to native through JSI.\n\nIt solves the **type-safety and boilerplate** problem: with the old bridge, JS and native agreed on method shapes by convention, and a mismatch failed silently at runtime. Codegen makes the typed spec the single source of truth and emits strongly-typed interfaces on both sides, so mismatches surface at build time.\n\nThe nuance: this is why New Architecture modules require typed specs — the generated artifacts are what actually wire the synchronous JSI calls, not hand-written marshalling.\n\n**Codegen turns the typed spec into the contract — a mismatch fails the build, not a user's device.**",
      "level": "senior"
    },
    {
      "id": "rn-render-1",
      "category": "rendering",
      "categoryLabel": "RENDERING & LISTS",
      "question": "What does React's `key` prop do during reconciliation, and what breaks when you use the array index as the key?",
      "answer": "During reconciliation React diffs the new element tree against the previous one. Within a list, the `key` is the identity React uses to match an old child to a new child, so it can **reuse, reorder, or unmount** the existing component instance (fiber) instead of rebuilding it.\n\nUsing the array index ties identity to position, not to the data. When the list reorders, inserts at the front, or filters, the data shifts under stable indices, so React reuses the wrong instance.\n\nConcrete failures:\n\n- Local state (a `useState` value, a `TextInput`'s text, scroll position) sticks to the slot and attaches to the wrong item.\n- Lost animation/mount continuity, because items are updated in place rather than treated as moved.\n- In virtualized lists it also defeats cell reuse and can show stale rows.\n\n- Red flag: defaulting to the array index as key for any list that can reorder, filter, or insert — this is the single most common wrong answer to this question.\n\nUse a stable, data-derived id (`item.id`). Index keys are only safe for a static list that never reorders, inserts, or filters.\n\n**Key is identity, not position — always derive it from the data, never from where it sits in the array.**",
      "level": "mid"
    },
    {
      "id": "rn-render-2",
      "category": "rendering",
      "categoryLabel": "RENDERING & LISTS",
      "question": "How does `FlatList` virtualization work, and what do `windowSize`, `initialNumToRender`, and `maxToRenderPerBatch` each control?",
      "answer": "`FlatList` (via `VirtualizedList`) mounts only the rows near the viewport and replaces off-screen rows with blank spacers sized to preserve scroll position, so mount cost and memory stay roughly constant instead of scaling with the dataset.\n\n- `windowSize` — how much content stays mounted, measured in **viewport-heights** (default `21`: the visible screen plus ~10 screens above and below). Lower it to cut memory; too low causes blank flashes on fast scroll.\n- `initialNumToRender` — rows rendered in the very first pass. Tune it to roughly fill the first screen for fast time-to-interactive; extra rows just delay first paint.\n- `maxToRenderPerBatch` — rows added per incremental batch while scrolling. Higher fills gaps faster but does more JS work per frame; lower keeps frames smooth at the cost of more visible blanks.\n\nSenior nuance: these trade **blank space vs JS-thread load**; tune them alongside `removeClippedSubviews` and `updateCellsBatchingPeriod` rather than one in isolation.\n\n**Every FlatList tuning knob trades blank space for JS-thread work — there's no setting that removes the trade-off.**",
      "level": "mid"
    },
    {
      "id": "rn-render-3",
      "category": "rendering",
      "categoryLabel": "RENDERING & LISTS",
      "question": "What problem does `getItemLayout` solve in `FlatList`, and when can't you use it?",
      "answer": "By default `FlatList` doesn't know a row's height until it has rendered and measured it, so it can't compute scroll offsets ahead of time. That makes `scrollToIndex`, `initialScrollIndex`, and scrollbar sizing unreliable and forces on-the-fly measurement.\n\n`getItemLayout={(data, index) => ({ length, offset, index })}` hands the list each row's height and cumulative offset analytically, so it can **skip measurement**. The wins: instant and correct `scrollToIndex`/`initialScrollIndex`, smoother scrolling, and less layout work.\n\nThe catch: it only works when item size is known up front and uniform (or cheaply computable from the index). For variable, content-dependent heights you can't give a correct `offset` without measuring, so you either eat the measurement cost or move to a list built for dynamic sizes — one reason teams reach for FlashList.\n\n**getItemLayout trades a measurement pass for an analytic formula — it only works when you can actually write that formula.**",
      "level": "senior"
    },
    {
      "id": "rn-render-4",
      "category": "rendering",
      "categoryLabel": "RENDERING & LISTS",
      "question": "Why is FlashList faster than `FlatList`? Describe the mechanism, not just \"it's optimized.\"",
      "answer": "`FlatList` virtualizes by **unmounting** off-screen cells and inserting blank spacers; recreating those component trees as you scroll is the expensive part and is what produces blank gaps on fast scroll.\n\nFlashList instead **recycles** a small pool of mounted views: when a row leaves the screen its view is re-bound to the incoming item's data rather than unmounted and re-created. This is the recycler pattern (like Android's `RecyclerView`), so view-creation cost is paid roughly once, not per scroll.\n\nIt also avoids a measure-then-render round trip by laying out cells from size estimates, and keeps more bookkeeping off the JS render path.\n\nSenior nuance: recycling is why you must reset per-row state on data change — derive UI purely from props, and use `getItemType` for heterogeneous rows so unlike layouts don't get recycled into each other. In FlashList v2 size estimation is automatic (`estimatedItemSize` is no longer required), but `getItemType` still matters.\n\n**FlatList unmounts and rebuilds off-screen cells; FlashList recycles them — that recycler pattern is the entire performance difference.**",
      "level": "senior"
    },
    {
      "id": "rn-render-5",
      "category": "rendering",
      "categoryLabel": "RENDERING & LISTS",
      "question": "What are the common `keyExtractor` pitfalls in a `FlatList`, and how do they show up at runtime?",
      "answer": "`keyExtractor` must return a **stable, unique string per item** (if omitted, `FlatList` falls back to `item.key`/`item.id`, then the index). The pitfalls:\n\n- Returning the index — ties identity to position, so reorders/inserts/filters reuse the wrong cell, exactly like index keys in plain React.\n- Non-unique keys — React logs a duplicate-key warning and reuses or drops cells unpredictably, causing flicker or missing rows.\n- Red flag: computing the key inside the extractor with `Math.random()`/`Date.now()` — a fresh key every render remounts every visible row each pass, destroying scroll performance.\n- Returning a non-string — the value is coerced via `String()`, so numbers can collide and objects all become `\"[object Object]\"`.\n\nThe fix is a deterministic id derived from the item, computed once, never re-randomized — and keep the extractor reference stable (`useCallback`) so the list prop doesn't churn.\n\n**A key must be deterministic and derived from the data — never randomized, never recomputed per render.**",
      "level": "mid"
    },
    {
      "id": "rn-render-6",
      "category": "rendering",
      "categoryLabel": "RENDERING & LISTS",
      "question": "Why do long lists drop frames in React Native, and where in the architecture does the jank originate?",
      "answer": "Your React render, diffing, and event handlers run on the **JS thread**, while the UI/native thread must produce a frame every ~16ms at 60fps (less on 120Hz displays). When JS work overruns that budget, the next frame is missed and scrolling stutters.\n\nLong-list jank usually traces to JS-thread saturation:\n\n- Rendering too many rows per batch (poor virtualization tuning), so each scroll does heavy element creation and diffing.\n- Expensive rows — inline functions/objects as props, unmemoized children, images decoded on the fly — re-rendering every pass.\n- Per-row work like layout measurement (no `getItemLayout`) or heavy mapping on each render.\n- On the old architecture, async bridge round-trips serializing scroll/layout data.\n\nFixes target the right layer: virtualize and tune batch sizes, `React.memo` rows with stable props, supply `getItemLayout` or switch to FlashList's recycling, and push heavy work off the JS thread (Reanimated worklets for animation, cached/resized images). The New Architecture (Fabric + JSI), now the RN default, removes the bridge bottleneck but doesn't excuse heavy render work.\n\n**The New Architecture removes the bridge bottleneck — it doesn't remove the need to keep JS-thread work off the critical path.**",
      "level": "senior"
    },
    {
      "id": "rn-perf-1",
      "category": "perf",
      "categoryLabel": "PERFORMANCE",
      "question": "A search input re-renders an entire list of cards on every keystroke. How do you find and fix the unnecessary re-renders?",
      "answer": "When a parent re-renders, React re-renders all of its children by default — the ones that didn't need to are the waste you're hunting.\n\n1. **Isolate**: open the **React DevTools Profiler** (now part of **React Native DevTools**) and record while typing.\n2. **Prove it**: read the \"why did this render\" reason — props changed, hooks changed, or parent rendered — instead of guessing which component is at fault.\n3. **Fix the specific cause**:\n   - State that should be **local** to the input lives high in the tree, so every keystroke re-renders siblings. Colocate it (move state down) or split the input into its own component.\n   - A new object/array/function literal passed as a prop breaks referential equality every render. Stabilize the reference, then wrap the child in `React.memo`.\n   - A **Context** value that's a fresh object each render re-renders every consumer; memoize the provider's `value`.\n\n**Colocate and split components before reaching for memoization — profile first, memoize last.**",
      "level": "mid"
    },
    {
      "id": "rn-perf-2",
      "category": "perf",
      "categoryLabel": "PERFORMANCE",
      "question": "When do React.memo, useMemo, or useCallback actively hurt performance instead of helping?",
      "answer": "All three add cost: they store the previous value/deps and run a comparison on every render. If the work they save is trivial, you pay the bookkeeping for nothing.\n\nWhere they backfire:\n\n- `React.memo` on a component whose props change reference every render runs a useless shallow compare and still re-renders.\n- `useCallback`/`useMemo` whose **dependency array** changes every render never hit the cache, and a wrong deps list can pin a stale closure.\n- Memoizing cheap work (string concat, small maps) costs more in comparison and memory than recomputing.\n\nThe nuance: `useCallback` only helps if the consumer is itself memoized or the function is another hook's dependency — otherwise a stable reference buys nothing. Reach for these after the Profiler shows a real, expensive re-render. The **React Compiler** auto-memoizes and is shifting this calculus toward writing plain code.\n\n**Memoization has a cost too — reach for it after the Profiler shows a real, expensive re-render, not by default.**",
      "level": "senior"
    },
    {
      "id": "rn-perf-3",
      "category": "perf",
      "categoryLabel": "PERFORMANCE",
      "question": "What does useNativeDriver: true actually do in an Animated animation, and what's the catch?",
      "answer": "`useNativeDriver: true` serializes the animation config up front and runs it on the **native UI thread**, so it doesn't cross to the JS thread frame by frame. The animation holds 60fps even when the JS thread is busy (a heavy render, a network response).\n\nThe catch: the native driver can only mutate properties that don't trigger layout — chiefly **`transform` and `opacity`** (color props like `backgroundColor` are also interpolatable natively). You cannot native-drive layout props like `width`, `height`, `top`, `margin`, or `flex`, because those need the layout engine on the JS side; trying warns and falls back.\n\nSenior nuance: this is the limitation **Reanimated** removes — it runs animation and gesture logic in worklets on the UI thread, including layout-driven work, instead of a fixed prop allowlist.\n\n**useNativeDriver only moves transform and opacity to the UI thread — anything layout-affecting still needs Reanimated.**",
      "level": "mid"
    },
    {
      "id": "rn-perf-4",
      "category": "perf",
      "categoryLabel": "PERFORMANCE",
      "question": "A screen janks for ~300ms while mounting a heavy list and running setup. How does InteractionManager help, and what are its limits?",
      "answer": "The jank is expensive JS running during the navigation transition, starving the JS thread the animation needs. `InteractionManager.runAfterInteractions(() => ...)` defers a callback until **after** running interactions/animations finish, so the transition stays smooth and the heavy work fires once the screen settles.\n\nUse it for non-urgent setup: prefetching secondary data, building expensive derived state, analytics, warming caches.\n\nLimits and nuance:\n\n- It only reorders work on the **same JS thread** — it doesn't make the work cheaper or parallel. A huge deferred task still janks, just later.\n- It's coarse; for animations specifically, moving them off the JS thread (`useNativeDriver`/Reanimated) is the real fix.\n- The modern alternative is React's `startTransition` / `useDeferredValue` to mark the heavy render low-priority, with `InteractionManager` reserved for imperative side effects.\n\n**InteractionManager reorders work on the same JS thread — it defers the cost, it doesn't remove it.**",
      "level": "senior"
    },
    {
      "id": "rn-perf-5",
      "category": "perf",
      "categoryLabel": "PERFORMANCE",
      "question": "What is TTI in a React Native app, what dominates cold-start time, and how does Hermes improve it?",
      "answer": "**TTI** (time to interactive) is from launch to when the user can tap and get a response — not just first pixel. Cold start = native init, then load and execute the JS bundle, then the first React render and layout.\n\nWhat dominates: parsing and evaluating the JS bundle. With JSC the engine parses and compiles JS at startup, scaling with bundle size.\n\n**Hermes** ships **precompiled bytecode**: the bundle is compiled ahead of time, so startup skips the JS parse/compile step and just loads bytecode. That cuts TTI and memory, especially on low-end Android. Hermes is the default engine.\n\nSenior levers beyond Hermes: lazy-load heavy screens, defer non-critical work past first interaction, trim what runs before first render, and use **inline requires** (with RAM bundles where applicable) so modules evaluate on demand. Measure cold-start TTI with a real tool (`react-native-performance`, EAS Observe, or a native trace) — not a stopwatch, and exclude warm starts.\n\n**TTI is bounded by what runs before first render — Hermes cuts the parse/compile step, inline requires cut what still runs eagerly.**",
      "level": "senior"
    },
    {
      "id": "rn-perf-6",
      "category": "perf",
      "categoryLabel": "PERFORMANCE",
      "question": "The JS bundle is bloated and startup is slow. How do you diagnose what's in it and shrink it?",
      "answer": "1. **Measure**: generate a treemap (`react-native-bundle-visualizer`, or Metro's `--sourcemap-output` fed to `source-map-explorer`) before cutting anything — see which modules and dependencies actually dominate bytes.\n2. **Cut dead weight**: kill accidental heavyweights — a full `moment`/`lodash` import, an entire icon set, duplicate libs — with per-method imports or lighter alternatives (`date-fns`, `dayjs`). Avoid barrel re-export files that defeat dead-code elimination; import from the specific path, since Metro tree-shaking is still limited/opt-in.\n3. **Move evaluation off the critical path**: **inline requires** (and RAM bundles) so modules evaluate lazily at first use instead of all at startup, and lazy-load rarely used screens behind dynamic `require`.\n\nNuance: bundle size and TTI are related but distinct — bytes drive download/OTA size, while what *runs before first render* drives startup.\n\n**Bundle size drives download/OTA cost; what runs before first render drives startup — inline requires fix the second without touching the first.**",
      "level": "senior"
    },
    {
      "id": "rn-anim-1",
      "category": "animations",
      "categoryLabel": "ANIMATIONS",
      "question": "What is a worklet in Reanimated, and why does running it on the UI thread matter for animations?",
      "answer": "A **worklet** is a JavaScript function marked (explicitly with `'worklet'` or implicitly inside hooks like `useAnimatedStyle`) that the Reanimated Babel plugin extracts so it can run on the **UI thread** in a separate JS runtime (the UI runtime), not the main JS thread.\n\nThis matters because the UI thread is the one that drives rendering. If your animation logic lives there, it can compute and commit each frame even while the JS thread is busy parsing JSON, running a heavy `useEffect`, or re-rendering a list.\n\nThe result is animations that hold 60/120fps independent of JS-thread load. The trade-off: a worklet captures its closure (shared values by reference, plain values by copy), and to call back into JS-thread code you need `runOnJS`.\n\n**A worklet runs on the UI thread by design — that's what lets animation logic survive a busy JS thread.**",
      "level": "mid"
    },
    {
      "id": "rn-anim-2",
      "category": "animations",
      "categoryLabel": "ANIMATIONS",
      "question": "Explain useSharedValue and useAnimatedStyle. Why update a shared value instead of component state?",
      "answer": "`useSharedValue` creates a mutable value (`sv.value`) shared between the JS and UI threads and readable/writable from worklets. `useAnimatedStyle` returns a style computed inside a worklet that automatically re-runs on the UI thread whenever a shared value it reads changes.\n\nMutating `sv.value` does **not** trigger a React render. Reanimated applies the new style directly to the native view on the UI thread, skipping the render/reconcile/commit cycle entirely.\n\n- State change = JS thread does a full render pass per frame, easily dropping frames.\n- Shared value change = native view updated on the UI thread, no render.\n\nSenior nuance: drive a swipe offset with a shared value and only push to state at gesture end, when React actually needs the final value.\n\n**Mutating a shared value skips React's render cycle entirely — that's the whole performance story.**",
      "level": "mid"
    },
    {
      "id": "rn-anim-3",
      "category": "animations",
      "categoryLabel": "ANIMATIONS",
      "question": "How does react-native-gesture-handler integrate with Reanimated, and why is it preferred over the RN PanResponder?",
      "answer": "`react-native-gesture-handler` recognizes gestures on the **native/UI thread** rather than in the JS responder system. Its `Gesture` callbacks (via `GestureDetector`) are worklets, so an `onUpdate` handler can mutate shared values and let `useAnimatedStyle` react, all without touching the JS thread.\n\n`PanResponder` runs in JS and routes every touch through the JS responder system, so a busy JS thread makes drags lag or drop touches.\n\nGesture handler also gives real native gesture composition (`Race`, `Simultaneous`, `Exclusive`) and proper interop with native scroll views. Senior point: hand off momentum in the gesture's `onEnd` with `withDecay`/`withSpring` so the fling animates entirely on the UI thread.\n\n**Gesture handler recognizes touches on the UI thread; PanResponder routes them through JS — that's why one drops frames under load and the other doesn't.**",
      "level": "senior"
    },
    {
      "id": "rn-anim-4",
      "category": "animations",
      "categoryLabel": "ANIMATIONS",
      "question": "What does useNativeDriver do in the Animated API, and what are its limitations?",
      "answer": "`useNativeDriver: true` serializes the animation node graph and its target values to native **once** at start, so the platform animates the view on the UI thread with no per-frame JS-thread callbacks.\n\nThe key limitation: the native driver only animates **non-layout properties** that don't require remeasuring, mainly `transform` and `opacity`. You cannot natively animate `width`, `height`, `top`, `left`, or `backgroundColor` (color interpolation is a partial exception on some setups, but layout props are out).\n\n- Red flag: animating `width`, `height`, `top`, or `left` with `useNativeDriver: true` — it warns and silently falls back to JS-driven frames instead of failing loudly.\n- Want to move something? Use `translateX`/`translateY`, not `left`/`top`.\n- Want to resize? Prefer `scale` over animating `width`/`height`.\n\nNuance: this is the classic-Animated constraint. Reanimated can drive any prop per frame from a worklet, but animating true layout props still forces native layout work, so transform/opacity stays the cheap path.\n\n**If it's not transform or opacity, useNativeDriver can't touch it.**",
      "level": "mid"
    },
    {
      "id": "rn-anim-5",
      "category": "animations",
      "categoryLabel": "ANIMATIONS",
      "question": "When would you reach for LayoutAnimation, and what are its sharp edges?",
      "answer": "`LayoutAnimation` animates the **next layout change** after a state update: call `LayoutAnimation.configureNext(...)` right before `setState`, and views that move/resize/appear tween to their new layout. It's ideal for cheap, fire-and-forget transitions like list insert/remove or expanding a card.\n\nSharp edges:\n\n- All-or-nothing for that commit, with no per-frame control or interruptibility.\n- On the old architecture / older Android you had to enable `setLayoutAnimationEnabledExperimental(true)`; it's effectively the default under the New Architecture (Fabric).\n- It can conflict with Reanimated layout animations, so don't mix them on the same tree.\n\nFor anything gesture-driven or interruptible, a senior reaches for Reanimated's `LinearTransition`/entering/exiting animations instead.\n\n**LayoutAnimation is fire-and-forget for cheap transitions; anything gesture-driven or interruptible needs Reanimated instead.**",
      "level": "senior"
    },
    {
      "id": "rn-anim-6",
      "category": "animations",
      "categoryLabel": "ANIMATIONS",
      "question": "Why does driving an animation through React state (e.g. setState in a loop or onScroll) cause jank?",
      "answer": "Each `setState` triggers a full React cycle on the **JS thread**: render, reconcile, diff, commit, then the new props cross to native. Doing that every frame burns the ~16ms budget on JS work instead of painting (under the New Architecture the JS↔native hop is synchronous JSI rather than the old async bridge, but it's still JS-thread work).\n\nIf any frame's JS overruns, the UI thread has no fresh value to render and you drop a frame; under load (list rendering, network parsing) the animation stutters because it's coupled to JS-thread availability.\n\n- Red flag: driving a continuous value — a drag offset, a scroll position — through `setState` on every frame. It couples the animation to JS-thread availability, so any JS work (a render, a fetch) drops frames.\n\nThe fix is to **decouple animation from the render cycle**: shared values + `useAnimatedStyle` (Reanimated) or `useNativeDriver`/`Animated.event`, so values update directly on the UI thread.\n\n**State is for discrete UI React owns; continuous per-frame values should never round-trip through React.**",
      "level": "senior"
    },
    {
      "id": "rn-nav-1",
      "category": "navigation",
      "categoryLabel": "NAVIGATION",
      "question": "In expo-router, how do files map to routes, and what does `_layout.tsx` do?",
      "answer": "expo-router is a **file-based** router built on React Navigation: every file in the `app/` directory becomes a route, and the path becomes the URL. `app/index.tsx` is `/`, `app/profile.tsx` is `/profile`, and `app/users/[id].tsx` is a dynamic route like `/users/42`.\n\nA `_layout.tsx` declares the **navigator** that wraps the routes in its directory (`Stack`, `Tabs`, `Drawer`) or renders children directly with `Slot`. It is where you put shared UI, providers, and per-screen options, and it stays mounted while its child routes change.\n\n- Folders group routes and can each carry their own `_layout`\n- `(group)` parentheses create a route group that organizes files **without** adding a URL segment\n- `+not-found.tsx` handles unmatched paths\n\n**In expo-router, the file tree is the router — a file's path and name is its route.**",
      "level": "junior"
    },
    {
      "id": "rn-nav-2",
      "category": "navigation",
      "categoryLabel": "NAVIGATION",
      "question": "When would you reach for a Stack vs a Tabs navigator, and how do you nest them?",
      "answer": "Use a **Stack** for a push/pop flow where screens build on each other and you want a back gesture and header (list to detail). Use **Tabs** for parallel top-level sections the user switches between freely, where each tab keeps its own state.\n\nThe common pattern nests a Stack **inside** each tab so every tab has independent history: `app/(tabs)/_layout.tsx` renders `<Tabs>`, and each tab folder has its own `_layout.tsx` rendering `<Stack>`. A senior nuance: by default inactive tab screens stay **mounted** (they are not unmounted on blur), so use focus effects and `freezeOnBlur` to pause work rather than relying on unmount, and keep expensive setup out of module top level.\n\n**Stack for sequential drill-down, Tabs for parallel sections — nest a Stack inside each tab so every tab keeps its own history.**",
      "level": "mid"
    },
    {
      "id": "rn-nav-3",
      "category": "navigation",
      "categoryLabel": "NAVIGATION",
      "question": "What are typed routes in expo-router and what do they buy you?",
      "answer": "Typed routes (`experiments.typedRoutes` in app config) make the dev server generate a `.d.ts` mapping of every route and its params from your `app/` tree. After that, `router.push`, `<Link href>`, and `useLocalSearchParams` are **statically typed**, so a path typo or a missing dynamic param is a TypeScript error instead of a runtime dead-end.\n\nThe practical win is refactor safety: rename or move a file and every navigation call to it fails to compile until fixed. The nuance is that the types are **generated**, so they can go stale until the dev server regenerates them, and an href built from a plain string escapes the checking unless you type it through the generated `Href` type.\n\n**Typed routes turn a renamed or moved file into a compile error at every call site, not a runtime dead end.**",
      "level": "senior"
    },
    {
      "id": "rn-nav-4",
      "category": "navigation",
      "categoryLabel": "NAVIGATION",
      "question": "Explain route params vs search params in expo-router, and the hooks to read each.",
      "answer": "Both arrive as strings on the same params object but come from different parts of the URL. **Route (path) params** are the dynamic segments declared by the filename, like `[id]` in `app/users/[id].tsx`, and are required to render that screen. **Search params** are the query string, like `?sort=asc`, and are optional.\n\nRead them with `useLocalSearchParams()` for params scoped to **this** screen, or `useGlobalSearchParams()` for params from the currently focused URL anywhere in the tree. A senior nuance: `useGlobalSearchParams` re-renders on **every** navigation change, so prefer `useLocalSearchParams` in deep screens to avoid spurious renders, and since everything is a string, coerce types yourself. Use `[...rest].tsx` for catch-all segments.\n\n**Route params are required and come from the filename; search params are optional and come from the query string.**",
      "level": "senior"
    },
    {
      "id": "rn-nav-5",
      "category": "navigation",
      "categoryLabel": "NAVIGATION",
      "question": "A tab screen stays mounted. How do you run logic only when it becomes visible vs hidden?",
      "answer": "Because tab screens stay mounted, `useEffect(..., [])` fires once at mount, not each time you return to the tab. For visibility-driven work use the focus lifecycle: `useFocusEffect(useCallback(() => { /* on focus */ return () => { /* on blur */ }; }, []))` runs on **focus** and cleans up on **blur**, every time.\n\nFor lighter needs, `useIsFocused()` returns a boolean to branch on, or subscribe via `navigation.addListener('focus' | 'blur', ...)`.\n\n- Red flag: relying on `useEffect(..., [])` to know when a tab becomes visible again — it fires once at mount, not on every return to the tab.\n\nA senior point: always wrap the `useFocusEffect` callback in `useCallback` or it re-subscribes on every render, and key off focus (not mount) to pause expensive things like video, polling, or location when a screen sits behind another tab.\n\n**Tab screens stay mounted — key visibility-driven work off focus/blur, not mount/unmount.**",
      "level": "mid"
    },
    {
      "id": "rn-nav-6",
      "category": "navigation",
      "categoryLabel": "NAVIGATION",
      "question": "How does deep linking work in expo-router, and how does it relate to React Navigation underneath?",
      "answer": "expo-router is a file-based layer over **React Navigation**: your `app/` tree compiles into a navigator config and a linking config automatically, so the URL is the source of truth for navigation state. Because paths map to files, deep links work out of the box: an incoming URL like `myapp://users/42` or an https App/Universal Link resolves to the matching route and params with no hand-written `linking` config.\n\nUnderneath, React Navigation still owns the **navigation state tree** and reconciles it from the URL; expo-router just generates that tree from the filesystem. Senior nuances: declare the custom `scheme` in app config and host an `apple-app-site-association` (iOS) and `assetlinks.json` (Android) for https links, deep-linking to a nested screen builds a sensible back stack, and you can inspect links with `Linking.getInitialURL()` and the `useURL()` hook.\n\n**expo-router generates React Navigation's linking config from your file tree — deep links just work because the URL already is the route.**",
      "level": "senior"
    },
    {
      "id": "rn-data-1",
      "category": "data",
      "categoryLabel": "STATE & DATA",
      "question": "One Context holds both rarely-changing config and frequently-changing UI state, and unrelated components keep re-rendering. Why, and how do you fix it?",
      "answer": "Every consumer of a Context re-renders whenever the **provider's `value` changes by reference**, no matter which field it actually reads. Context has no selector, so a fast-changing field drags slow consumers along with it.\n\nThe senior fix is to **split context by update frequency**, not by domain: stable data (theme, current user) in one provider, volatile data in another, so a config-only consumer never re-renders on a volatile change.\n\n- Red flag: treating Context as a general-purpose state manager — it has no selectors, so every consumer re-renders on any provider value change, no matter which field it actually reads.\n- Memoize `value` with `useMemo` so the provider doesn't hand out a fresh object every render.\n- Split state and dispatch into two contexts so action-only consumers don't re-render on state changes (`dispatch` is referentially stable).\n- When splitting isn't enough, use an external store (`useSyncExternalStore`, Zustand, Jotai) that supports **selector-based subscriptions**.\n\n**Split context by update frequency, not by domain — reach for a store with selectors once splitting isn't enough.**",
      "level": "mid"
    },
    {
      "id": "rn-data-2",
      "category": "data",
      "categoryLabel": "STATE & DATA",
      "question": "Explain stale-while-revalidate in React Query, and the role of `staleTime` versus `gcTime` (formerly `cacheTime`).",
      "answer": "**Stale-while-revalidate** means a query immediately returns cached data (even if stale) so the UI paints instantly, then refetches in the background and swaps in fresh data — you never block on the network for data you already have.\n\n- `staleTime` controls **when** data becomes stale. While fresh (within `staleTime`), React Query serves the cache and skips refetching on mount, focus, or reconnect. Default is `0`, so data is stale immediately.\n- `gcTime` (renamed from `cacheTime` in v5) controls **how long** an inactive query's data lingers after its last observer unmounts, before garbage collection. Default is 5 minutes.\n\nThe nuance: `staleTime` governs freshness/refetch decisions, `gcTime` governs retention. On mobile, raise `staleTime` to cut redundant refetches, since `focusManager` ties `refetchOnWindowFocus` to RN's `AppState`, which fires often.\n\n**staleTime decides whether to refetch; gcTime decides how long to keep the cache after nobody's watching.**",
      "level": "senior"
    },
    {
      "id": "rn-data-3",
      "category": "data",
      "categoryLabel": "STATE & DATA",
      "question": "Why must React state updates be immutable, and what's a concrete bug from mutating state directly?",
      "answer": "React decides whether to re-render via a **shallow reference comparison** (`Object.is`) of state and props. Mutate an object or array in place and the reference is unchanged, so React (and `memo`/`useMemo`/`useEffect` dependency arrays) sees \"no change\" and skips the update — the UI goes stale.\n\nA classic bug: `items.push(newItem); setItems(items)` passes the **same array reference**, so a memoized `FlatList` or child never re-renders. The fix produces a new reference: `setItems(prev => [...prev, newItem])`.\n\n- Use functional updates (`setX(prev => ...)`) to avoid stale-closure bugs in batched or async updates.\n- For deep/nested updates, reach for Immer (`produce`) to write \"mutative\" code that yields a new immutable tree — this is what Redux Toolkit uses under the hood.\n\n**React skips re-renders on same-reference state — mutate in place and the UI silently goes stale.**",
      "level": "junior"
    },
    {
      "id": "rn-data-4",
      "category": "data",
      "categoryLabel": "STATE & DATA",
      "question": "What are the real limitations of AsyncStorage, and when would you reach for something else?",
      "answer": "`AsyncStorage` is an **unencrypted, asynchronous, key-value store of strings**, backed by SQLite on Android and flat files on iOS. It's fine for small, non-sensitive data like flags, cache, or onboarding state, but it has real limits.\n\n- Red flag: storing auth tokens, passwords, or PII in AsyncStorage — it's unencrypted. Use `expo-secure-store` / Keychain / Keystore instead.\n- **Strings only** — you must `JSON.stringify`/`parse`, and the async API means every access is a promise you have to await, which invites race conditions.\n- **Not relational or queryable** — for structured or large datasets use SQLite (`expo-sqlite`) or WatermelonDB, or for fast key-value use **MMKV**, which is synchronous and supports encryption.\n\nSenior nuance: MMKV's synchronous, memory-mapped API removes the whole class of await-ordering races you get from AsyncStorage, and avoids JSON round-trips for primitives.\n\n**AsyncStorage is for cheap, non-sensitive data — tokens and PII belong in secure storage, not a JSON blob.**",
      "level": "mid"
    },
    {
      "id": "rn-data-5",
      "category": "data",
      "categoryLabel": "STATE & DATA",
      "question": "Walk through an optimistic update with React Query, including rollback. Why is `onMutate` the key?",
      "answer": "An optimistic update writes the expected result to the cache **before** the server confirms, so the UI feels instant for a **mutation** — you reconcile or roll back once it settles. `useMutation`'s lifecycle callbacks are built for exactly this sequence.\n\n1. **onMutate**: call `queryClient.cancelQueries` (so an in-flight refetch can't clobber your write), snapshot current data with `getQueryData`, then `setQueryData` to the optimistic value. Return the snapshot — it becomes the **context** passed to later callbacks.\n2. **onError**: restore that snapshot via `setQueryData` — the rollback.\n3. **onSettled**: `invalidateQueries` to refetch and converge on server truth, on success or failure.\n\n- Red flag: reaching for optimistic updates on an **initial load** — that's what staged/skeleton loading is for. Optimistic updates are for mutations where you already know the expected result.\n\n**Cancelling queries and snapshotting in onMutate is what makes rollback deterministic under concurrency.**",
      "level": "senior"
    },
    {
      "id": "rn-data-6",
      "category": "data",
      "categoryLabel": "STATE & DATA",
      "question": "How would you architect an offline-first app where users create and edit data with no connectivity?",
      "answer": "Offline-first means the **local store is the source of truth** for the UI, and the network is a background sync concern — the app is fully usable offline and reconciles when connectivity returns.\n\n- Persist data plus a **mutation/outbox queue** locally (SQLite, WatermelonDB, or React Query's `persistQueryClient` with offline mutations). Writes hit the local store immediately and enqueue a pending sync op.\n- Detect connectivity with `@react-native-community/netinfo` (wired into React Query's `onlineManager`), which **pauses** mutations offline and resumes them on reconnect.\n- Plan for **conflict resolution**: last-write-wins is simplest; for collaborative data use server versions/timestamps or CRDTs. Give each op a client-generated **idempotency key** so retries don't double-apply.\n\nSenior nuance: mint record IDs client-side (UUIDs) so optimistic records have stable identity before the server sees them, avoiding the \"temp id vs real id\" remapping problem.\n\nPitched to a skeptic who'd rather skip this: yes, an outbox queue and conflict resolution is real upfront engineering cost. But the alternative — a network-only app — means every flaky-connectivity moment (subway, elevator, weak signal) either blocks the user or silently drops their write, a worse and harder-to-debug failure than the extra build time. Treat it as investment: the queue and idempotency keys you build for offline-first are the same infrastructure that makes retries safe on a merely slow connection, online or off. At scale, the lifecycle cost is real too — an outbox queue or CRDT tombstone history that never gets garbage-collected is its own future incident.\n\n**Local-first with an outbox queue turns flaky connectivity into a sync problem instead of a data-loss problem.**",
      "level": "architect"
    },
    {
      "id": "rn-native-1",
      "category": "native",
      "categoryLabel": "NATIVE MODULES",
      "question": "What problem does the Expo Modules API solve, and how does it differ from writing a classic React Native bridge module?",
      "answer": "The Expo Modules API is a Swift/Kotlin DSL for authoring native modules without hand-writing the boilerplate, type marshalling, and threading glue the old bridge required.\n\nInstead of conforming to `RCTBridgeModule` and manually exporting methods with macros, you declare a `Module` with a `definition` block built from `Function`, `AsyncFunction`, `Property`, `Events`, and lifecycle hooks like `OnCreate`/`OnDestroy`. The API auto-converts JS-to-native types, including records, enums, and shared objects.\n\nThe senior nuance: it talks to the JS runtime over JSI rather than the async, JSON-serialized bridge, so `Function` can run synchronously (blocking the JS thread until it returns) and the module works under the New Architecture without you hand-authoring a separate TurboModule spec.\n\n**The Expo Modules API generates the marshalling and JSI wiring that a classic bridge module made you hand-write.**",
      "level": "mid"
    },
    {
      "id": "rn-native-2",
      "category": "native",
      "categoryLabel": "NATIVE MODULES",
      "question": "Walk me through implementing a simple native module in Swift and Kotlin with the Expo Modules API.",
      "answer": "You write one class per platform that subclasses `Module` and returns a `ModuleDefinition` from its `definition()`.\n\n1. `Name(\"MyModule\")` sets the JS-visible name you later pass to `requireNativeModule`.\n2. `Function(\"add\") { (a: Int, b: Int) in a + b }` for a synchronous call on the JS thread; use `AsyncFunction` for work that should run off it or that resolves a `Promise`.\n3. `Property(\"version\") { ... }` for a getter; `Events(\"onChange\")` to declare events you fire with `sendEvent`.\n4. `Constants([...])` to expose static values read at init.\n\nSwift uses trailing closures and `throws`; Kotlin mirrors the same DSL with lambdas. On the TS side you wrap it with `requireNativeModule<MyModuleType>('MyModule')` so callers get a typed surface.\n\n**The definition block is the entire contract — name, functions, properties, and events, nothing hand-marshalled.**",
      "level": "mid"
    },
    {
      "id": "rn-native-3",
      "category": "native",
      "categoryLabel": "NATIVE MODULES",
      "question": "What are TurboModules and Codegen, and how do they change native modules under the New Architecture?",
      "answer": "TurboModules are the New Architecture replacement for legacy bridge native modules: they load lazily and are invoked directly over JSI instead of through the async, batched, JSON-serialized bridge, cutting startup cost and per-call latency.\n\nCodegen is the build-time tool that reads your TypeScript (or Flow) spec — a file named `Native<Name>` whose interface extends `TurboModule` and is exported via `TurboModuleRegistry.getEnforcing` — and emits the C++/Obj-C/Java interface glue, making the JS-to-native contract statically typed.\n\nThe senior nuance: the spec is the single source of truth, so Codegen runs during the build (`pod install` / Gradle) and a mismatch between spec and native implementation fails to compile rather than crashing at runtime. The Expo Modules API hides most of this, but knowing the flow matters when debugging third-party TurboModules.\n\n**Codegen makes the spec the single source of truth — a mismatch fails the build, not a user's runtime.**",
      "level": "senior"
    },
    {
      "id": "rn-native-4",
      "category": "native",
      "categoryLabel": "NATIVE MODULES",
      "question": "What is a config plugin, when do you need one, and why can't you just edit the native projects directly?",
      "answer": "A config plugin is a JavaScript function that mutates the generated native iOS/Android projects during `npx expo prebuild`, letting you apply native changes (Info.plist keys, AndroidManifest entries, Gradle/Podfile tweaks, entitlements) declaratively from your Expo config.\n\nYou need one under Continuous Native Generation, where `ios/` and `android/` are generated and usually not committed.\n\n- Red flag: hand-editing the generated `ios/`/`android/` projects directly — the next `prebuild` silently regenerates and overwrites the change, so it must live in a plugin to be reproducible.\n\nMechanically you compose mods like `withInfoPlist`, `withAndroidManifest`, and `withDangerousMod`; well-published modules ship their own plugin so consumers just add it to `plugins` in `app.json`. The nuance: prefer the typed mod helpers over `withDangerousMod`, which performs raw filesystem edits with no merge safety.\n\n**If it's not in a config plugin, the next prebuild will erase it.**",
      "level": "senior"
    },
    {
      "id": "rn-native-5",
      "category": "native",
      "categoryLabel": "NATIVE MODULES",
      "question": "How do platform-specific files (.ios/.android) work, and how do you handle permissions in an Expo app?",
      "answer": "Metro resolves platform extensions automatically: importing `./Foo` with no extension picks `Foo.ios.tsx`, `Foo.android.tsx` (also `.native` and `.web`) per platform, so you can fork an implementation without runtime branching. `Platform.OS` and `Platform.select` cover smaller inline differences.\n\nPermissions are two parts: a runtime request API on the relevant module (e.g. `requestCameraPermissionsAsync`) plus a native declaration the OS requires — `NSCameraUsageDescription` in `Info.plist` and a `uses-permission` entry in `AndroidManifest.xml`.\n\nThe senior nuance: those native declarations should come from the module's config plugin or the `ios`/`android.permissions` fields in app config rather than hand edits, and on iOS accessing a protected API with no usage-description string makes the OS terminate the app outright, not just deny the prompt.\n\n**A permission needs both a runtime request and a native usage-description string — skip the second and the OS kills the app outright.**",
      "level": "mid"
    },
    {
      "id": "rn-native-6",
      "category": "native",
      "categoryLabel": "NATIVE MODULES",
      "question": "Explain autolinking. How does Expo know to compile a native module without you touching Xcode or Gradle?",
      "answer": "Autolinking discovers native modules from your installed npm dependencies and wires them into the iOS and Android builds automatically, replacing the old manual `react-native link` step.\n\nReact Native core autolinking scans your dependency tree for packages that ship a native podspec/Gradle project (with `react-native.config.js` available to override or disable the defaults) and feeds them to CocoaPods and Gradle. Expo adds a layer on top: `expo-modules-autolinking` finds packages declaring an `expo-module.config.json` and registers their Swift/Kotlin modules with the generated `ModulesProvider` at build time.\n\nThe senior nuance: resolution happens at build time from the dependency graph, so you can exclude or override modules via the `expo.autolinking` config or RN's `dependencies` block, and a module that never appears is almost always a missing `expo-module.config.json` or a package the resolver couldn't see in a hoisted `node_modules`.\n\n**Autolinking replaces manual linking by discovering native modules from your dependency graph at build time.**",
      "level": "senior"
    },
    {
      "id": "rn-test-1",
      "category": "testing",
      "categoryLabel": "TESTING",
      "question": "Why use the `jest-expo` preset instead of plain `jest` or React Native's preset for an Expo app?",
      "answer": "`jest-expo` ships a preset tuned to your Expo SDK: it sets `transformIgnorePatterns` so the untranspiled ESM/Flow/TS that Expo, React Native, and many community packages ship in `node_modules` actually gets run through Babel, it mocks Expo's native modules, and it can run one suite across `ios`, `android`, and `web` via `jest-expo/multi-project`.\n\nThe failure plain Jest hits first is `SyntaxError: Cannot use import statement outside a module`, because Jest ignores `node_modules` by default and those packages aren't pre-compiled. `jest-expo` already whitelists them.\n\nNuance: it pins a `react-test-renderer` and RN Jest preset compatible with your SDK.\n\n- Red flag: hand-installing your own `react-test-renderer` — `jest-expo` already bundles one pinned to your SDK, and version drift against it is a frequent source of cryptic errors.\n\n**jest-expo exists because plain Jest doesn't transpile the untranspiled ESM/Flow/TS that RN packages ship in node_modules.**",
      "level": "mid"
    },
    {
      "id": "rn-test-2",
      "category": "testing",
      "categoryLabel": "TESTING",
      "question": "In React Native Testing Library, when do you reach for `getBy*` vs `queryBy*` vs `findBy*`?",
      "answer": "Pick the query by whether the element is already there and whether it's async:\n\n- `getBy*` — element should already be present; throws if missing or if multiple match. Use for synchronous assertions.\n- `queryBy*` — returns `null` instead of throwing; the only correct way to assert absence (`expect(queryByText('x')).toBeNull()`).\n- `findBy*` — returns a Promise that retries until the element appears or times out; use it for anything rendered after an async effect, fetch, or state update.\n\nNuance: `findBy*` is `getBy*` wrapped in `waitFor`, so `await findByText(...)` already flushes pending updates — you rarely need a manual `waitFor` around it, and it keeps you out of `act()` warnings.\n\n**getBy for what's there, queryBy for what should be absent, findBy for what's coming.**",
      "level": "mid"
    },
    {
      "id": "rn-test-3",
      "category": "testing",
      "categoryLabel": "TESTING",
      "question": "What is `waitFor` actually doing, and what's the most common way people misuse it?",
      "answer": "`waitFor` re-runs the callback you pass it on an interval until it stops throwing (or hits the timeout), then resolves. It's for waiting on an assertion to become true after async work — a re-render, a resolved promise, a timer.\n\n- Red flag: putting **side effects** (like `fireEvent.press`) or multiple assertions inside the `waitFor` callback. Because the body re-runs many times, a side effect fires repeatedly and an earlier failure can be masked by a later assertion. Keep the callback to a single, side-effect-free assertion.\n\nNuance: prefer `await findBy*` when you're just waiting for an element; reach for `waitFor` for non-query conditions like a mock having been called or text disappearing. Under fake timers, advance them (`jest.advanceTimersByTime`) or `waitFor` never settles.\n\n**waitFor is for waiting on a condition to become true, not for triggering it.**",
      "level": "senior"
    },
    {
      "id": "rn-test-4",
      "category": "testing",
      "categoryLabel": "TESTING",
      "question": "How do you mock a native module — say a TurboModule or a library like `react-native-keychain` — in Jest?",
      "answer": "A native module has no JS implementation under Node, so you replace it with a test double. Common approaches:\n\n- `jest.mock('react-native-keychain', () => ({ setGenericPassword: jest.fn(), getGenericPassword: jest.fn().mockResolvedValue(false) }))` — module-level mock with controllable returns.\n- For Expo modules, rely on `jest-expo` (it mocks most) and override specifics with `jest.mock`.\n- If a library ships its own mock, register it once in a setup file referenced by `setupFiles` so every test gets it.\n\nNuance: match the real shape — if the API returns a Promise, the mock must too (`mockResolvedValue`) or `await` calls hang. For modules reached via `NativeModules.Foo`, mock that object rather than the JS wrapper, and `jest.clearAllMocks()` in `afterEach` so call counts don't leak between tests.\n\n**Mock the shape the real module returns — if it resolves a Promise, the mock must too, or awaits hang.**",
      "level": "senior"
    },
    {
      "id": "rn-test-5",
      "category": "testing",
      "categoryLabel": "TESTING",
      "question": "Maestro vs Detox for end-to-end testing — how do you choose, and what's the core trade-off?",
      "answer": "Both drive a real build on a simulator/emulator, but the philosophies differ:\n\n- **Maestro** is black-box: declarative YAML flows (`launchApp`, `tapOn`, `assertVisible`) that match by accessibility id or visible text, with built-in implicit waits and retries — so flows are less flaky and need almost no app instrumentation. Faster to author and maintain.\n- **Detox** is grey-box: it hooks the app's runtime to know when the JS thread is idle, giving deterministic synchronization, but you wire `testID`s carefully and own more setup.\n\nFor most RN/Expo teams Maestro wins on author speed and stability; Detox earns its keep when you need tight runtime sync or fine-grained control. Either way, stable `testID`/accessibility ids are the contract between app and flow.\n\nNuance: neither drives Expo Go — you need a dev-client or standalone build installed — and both slot into CI on EAS Workflows or GitHub Actions.\n\n**Maestro trades runtime control for authoring speed and stability; Detox trades setup cost for deterministic JS-thread sync.**",
      "level": "senior"
    },
    {
      "id": "rn-test-6",
      "category": "testing",
      "categoryLabel": "TESTING",
      "question": "On Hermes, how do you debug with React Native DevTools, and why doesn't the old Chrome 'Remote JS Debugging' apply?",
      "answer": "On Hermes you open **React Native DevTools** from the Dev Menu (`j` in the Metro terminal). It's a Chrome-DevTools-based frontend that connects to Hermes over the **Chrome DevTools Protocol (CDP)** through Metro's inspector proxy, giving breakpoints, stepping, the console, and a CPU/memory profiler that run against the actual on-device JS engine.\n\n- Red flag: reaching for the legacy 'Remote JS Debugging' on Hermes — it ran your JS in Chrome's V8 in a separate process, which changed timing and broke synchronous native (JSI/TurboModule) calls. It's misleading on Hermes and now deprecated/removed for exactly that reason.\n\nDebugging in-engine means what you see matches production behavior.\n\nNuance: for perf work Hermes can emit a sampling profile you load into DevTools or Perfetto, and source maps must be wired up so stack traces and breakpoints map to your TypeScript rather than the bundled output.\n\n**Debug in the engine that ships to production — React Native DevTools talks to Hermes directly over CDP, no separate JS runtime in the loop.**",
      "level": "senior"
    }
  ]
};
